In [1]:
! pip install git+https://github.com/probberechts/soccerdata.git@252809cc294f88eabc207caa41b91187dc6739c3

Collecting git+https://github.com/probberechts/soccerdata.git@252809cc294f88eabc207caa41b91187dc6739c3
  Cloning https://github.com/probberechts/soccerdata.git (to revision 252809cc294f88eabc207caa41b91187dc6739c3) to /private/var/folders/zp/brhyd_7s1tn3snjbt6nxh0kr0000gn/T/pip-req-build-704v7ucm
  Running command git clone --filter=blob:none --quiet https://github.com/probberechts/soccerdata.git /private/var/folders/zp/brhyd_7s1tn3snjbt6nxh0kr0000gn/T/pip-req-build-704v7ucm
  Running command git rev-parse -q --verify 'sha^252809cc294f88eabc207caa41b91187dc6739c3'
  Running command git fetch -q https://github.com/probberechts/soccerdata.git 252809cc294f88eabc207caa41b91187dc6739c3
  Resolved https://github.com/probberechts/soccerdata.git to commit 252809cc294f88eabc207caa41b91187dc6739c3
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: PySocks<2.0.0,>=1.7.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from soccerdata==1.5.1) (1.7.1)
Requirement already satisfied: Unidecode<2.0.0,>=1.2.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from soccerdata==1.5.1) (1.3.7)
Requirement already satisfied: html5lib<2.0,>=1.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from soccerdata==1.5.1) (1.1)
Requirement already satisfied: lxml<5.0,>=4.6 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from soccerdata==1.5.1) (4.9.3)
Requirement already satisfied: pandas<3.0.0,>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from soccerdata==1.5.1) (2.0.3)
Requirement already satisfied: requests<3.0,>=2.23 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from soccerdata==1.5.1) (2.31.0)
Requirement already satisfied: rich<14.0.0,>=13.0.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from soccerdata==1.5.1) (13.4.2)
Requirement already satisfied: undetected-chromedriver<4.0.0,>=3.5.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from soccerdata==1.5.1) (3.5.3)
Requirement already satisfied: unicode<3.0,>=2.7 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from soccerdata==1.5.1) (2.9)
Requirement already satisfied: six>=1.9 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from html5lib<2.0,>=1.1->soccerdata==1.5.1) (1.15.0)
Requirement already satisfied: webencodings in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from html5lib<2.0,>=1.1->soccerdata==1.5.1) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pandas<3.0.0,>=2.0.0->soccerdata==1.5.1) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pandas<3.0.0,>=2.0.0->soccerdata==1.5.1) (2022.1)
Requirement already satisfied: tzdata>=2022.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pandas<3.0.0,>=2.0.0->soccerdata==1.5.1) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pandas<3.0.0,>=2.0.0->soccerdata==1.5.1) (1.22.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests<3.0,>=2.23->soccerdata==1.5.1) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests<3.0,>=2.23->soccerdata==1.5.1) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests<3.0,>=2.23->soccerdata==1.5.1) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests<3.0,>=2.23->soccerdata==1.5.1) (2022.6.15.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from rich<14.0.0,>=13.0.0->soccerdata==1.5.1) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from rich<14.0.0,>=13.0.0->soccerdata==1.5.1) (2.15.1)
Requirement already satisfied: typing-extensions<5.0,>=4.0.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from rich<14.0.0,>=13.0.0->soccerdata==1.5.1) (4.7.1)
Requirement already satisfied: selenium>=4.9.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from undetected-chromedriver<4.0.0,>=3.5.0->soccerdata==1.5.1) (4.13.0)
Requirement already satisfied: websockets in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from undetected-chromedriver<4.0.0,>=3.5.0->soccerdata==1.5.1) (11.0.3)
Requirement already satisfied: mdurl~=0.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from markdown-it-py>=2.2.0->rich<14.0.0,>=13.0.0->soccerdata==1.5.1) (0.1.2)
Requirement already satisfied: trio~=0.17 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from selenium>=4.9.0->undetected-chromedriver<4.0.0,>=3.5.0->soccerdata==1.5.1) (0.22.2)
Requirement already satisfied: trio-websocket~=0.9 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from selenium>=4.9.0->undetected-chromedriver<4.0.0,>=3.5.0->soccerdata==1.5.1) (0.11.1)
Requirement already satisfied: attrs>=20.1.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from trio~=0.17->selenium>=4.9.0->undetected-chromedriver<4.0.0,>=3.5.0->soccerdata==1.5.1) (23.1.0)
Requirement already satisfied: sortedcontainers in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from trio~=0.17->selenium>=4.9.0->undetected-chromedriver<4.0.0,>=3.5.0->soccerdata==1.5.1) (2.4.0)
Requirement already satisfied: outcome in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from trio~=0.17->selenium>=4.9.0->undetected-chromedriver<4.0.0,>=3.5.0->soccerdata==1.5.1) (1.2.0)
Requirement already satisfied: sniffio in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from trio~=0.17->selenium>=4.9.0->undetected-chromedriver<4.0.0,>=3.5.0->soccerdata==1.5.1) (1.3.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from trio~=0.17->selenium>=4.9.0->undetected-chromedriver<4.0.0,>=3.5.0->soccerdata==1.5.1) (1.1.2)
Requirement already satisfied: wsproto>=0.14 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from trio-websocket~=0.9->selenium>=4.9.0->undetected-chromedriver<4.0.0,>=3.5.0->soccerdata==1.5.1) (1.2.0)
Requirement already satisfied: h11<1,>=0.9.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium>=4.9.0->undetected-chromedriver<4.0.0,>=3.5.0->soccerdata==1.5.1) (0.14.0)

In [420]:
import soccerdata as sd
import pandas as pd
from datetime import date as d, timedelta, datetime

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)

In [386]:
fifa = sd.SoFIFA('ENG-Premier League')
fifa.read_player_ratings()

[10/06/23 13:28:27] INFO     Saving cached data to /Users/Gautham/soccerdata/data/SoFIFA              ]8;id=804175;file:///Users/Gautham/miniconda3/envs/dl_hw1/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=637681;file:///Users/Gautham/miniconda3/envs/dl_hw1/lib/python3.10/site-packages/soccerdata/_common.py#89\89]8;;\

league_id                        league
0          13      [England] Premier League
1          16              [France] Ligue 1
2          19          [Germany] Bundesliga
3          31               [Italy] Serie A
4          53               [Spain] La Liga
..        ...                           ...
45       2018            [Ecuador] Liga Pro
46       2019  [Venezuela] Primera Division
47       2020       [Peru] Primera Division
48       2076             [Germany] 3. Liga
49       2149   [India] Indian Super League

[50 rows x 2 columns]

[10/06/23 13:28:30] INFO     [1/1] Retrieving teams for ENG-Premier League in Oct 5, 2023 edition     ]8;id=817481;file:///Users/Gautham/miniconda3/envs/dl_hw1/lib/python3.10/site-packages/soccerdata/sofifa.py\sofifa.py]8;;\:]8;id=818573;file:///Users/Gautham/miniconda3/envs/dl_hw1/lib/python3.10/site-packages/soccerdata/sofifa.py#185\185]8;;\

IndexError: list index out of range

In [396]:
TEAM_DIC = {
'Middlesboro': 'Middlesbrough',
"Nott'm Forest": 'Forest',
'Newcastle Utd': 'Newcastle',
'Luton Town': 'Luton',
'Manchester City': 'Man City',
'Manchester Utd': 'Man United',
'Sheffield Utd': 'Sheffield United',
"Nott'ham Forest": 'Forest',
"Nottingham Forest": 'Forest',
'Manchester United': 'Man United',
'Wolverhampton Wanderers': 'Wolves',
'Leicester City': 'Leicester',
'Newcastle United': 'Newcastle',
'Queens Park Rangers': 'QPR',
'West Bromwich Albion': 'West Brom',
'Brighton and Hove Albion': 'Brighton',
'Brighton & Hove Albion': 'Brighton',
'West Ham United': 'West Ham',
'Tottenham Hotspur': 'Tottenham',
'AFC Bournemouth': 'Bournemouth',
'Blackburn Rovers': 'Blackburn',
'Bolton Wanderers': 'Bolton',
'Birmingham City': 'Birmingham',
'Wigan Athletic': 'Wigan',
'Stoke City': 'Stoke',
'Hull City': 'Hull',
'Swansea City': 'Swansea',
'Norwich City': 'Norwich',
'Cardiff City': 'Cardiff',
'Huddersfield Town': 'Huddersfield',
'Leeds United': 'Leeds',

'Vallecano': 'Rayo Vallecano', 
'Ath Bilbao': 'Bilbao', 
'Ath Madrid': 'Atletico', 
'Espanol': 'Espanyol', 
'Sp Gijon': 'Gijon', 
'Celta Vigo': 'Celta', 
'Atlético Madrid': 'Atletico', 
'Athletic Club': 'Bilbao',
'Real Sociedad': 'Sociedad',
'Almería': 'Almeria',
'Cádiz': 'Cadiz',
'Alavés': 'Alaves',
'Hellas Verona': 'Verona',
'Atletico Madrid': 'Atletico', 
'Sporting Gijon': 'Gijon',
'Real Betis': 'Betis',
'Real Valladolid': 'Valladolid',
'SD Huesca': 'Huesca',
'Deportivo Alavés': 'Alaves',
'Celta de Vigo': 'Celta',
'FC Barcelona': 'Barcelona',
'Sporting Gijón': 'Gijon',
'Real Zaragoza': 'Zaragoza',
'Málaga': 'Malaga',
'Racing Santander': 'Santander',
'Deportivo La Coruña': 'La Coruna',
'Hércules': 'Hercules',
'SD Eibar': 'Eibar',
'Córdoba': 'Cordoba',
'Leganés': 'Leganes'
}
class MissingDict(dict):
    __missing__ = lambda self, key: key

mapping = MissingDict(**TEAM_DIC)

In [397]:
fifa = pd.read_csv('/Users/Gautham/Projects/sports_betting/cache/LaLiga/fifa.csv')
rolling = pd.read_csv('/Users/Gautham/Projects/sports_betting/src/elo_test.csv')
new = pd.read_csv('/Users/Gautham/Projects/sports_betting/cache/LaLiga/new.csv')

In [398]:
fifa['update'] = pd.to_datetime(fifa['update'])
fifa = fifa.rename(columns={'defence': 'defense'})#, 'update': 'Date'})

fifa['team'] = fifa['team'].map(mapping)
fifa = fifa.drop_duplicates(['team', 'update']).sort_values('update')
rolling['Date'] = pd.to_datetime(rolling['Date'])

In [399]:
fifa

,league,team,overall,attack,midfield,defense,transfer_budget,players,fifa_edition,update
0,ESP-La Liga,Real Madrid,85,85,85,83,€0,33,FIFA 07,2006-08-30
19,ESP-La Liga,Alaves,72,73,73,73,€0,28,FIFA 07,2006-08-30
18,ESP-La Liga,Granada,73,76,72,72,€0,29,FIFA 07,2006-08-30
17,ESP-La Liga,Las Palmas,74,75,75,72,€0,27,FIFA 07,2006-08-30
16,ESP-La Liga,Valencia,75,74,74,76,€0,30,FIFA 07,2006-08-30
...,...,...,...,...,...,...,...,...,...,...
14481,ESP-La Liga,Barcelona,84,84,84,83,€0,32,FC 24,2023-10-05
14480,ESP-La Liga,Real Madrid,85,85,85,83,€0,33,FC 24,2023-10-05
14498,ESP-La Liga,Granada,73,76,72,72,€0,29,FC 24,2023-10-05
14488,ESP-La Liga,Osasuna,77,77,77,77,€0,32,FC 24,2023-10-05
14499,ESP-La Liga,Alaves,72,73,73,73,€0,28,FC 24,2023-10-05

In [400]:
li1 = fifa['team'].unique()
s = set(list(new['Team'].unique()) + list(new['Opponent'].unique()))
print('teams with different names:', [x for x in li1 if x not in s])
#li1

teams with different names: ['Xerez', 'Tenerife', 'Zaragoza', 'Santander', 'La Coruna', 'Hercules']

In [370]:
rolling = pd.merge_asof(rolling, fifa[['update', 'team', 'overall', 'attack', 'midfield', 'defense']], left_on='Date', right_on='update', left_by=['Team'], right_by='team', direction='backward')#, tolerance=pd.Timedelta(days=365))
df = pd.merge_asof(rolling, fifa[['update', 'team', 'overall', 'attack', 'midfield', 'defense']], left_on='Date', right_on='update', left_by=['Opponent'], right_by='team', direction='backward')#, tolerance=pd.Timedelta(days=365))

In [371]:
df.columns = [f'Team{x.title()[:-2]}RatingFIFA' if '_x' in x else f'Opponent{x.title()[:-2]}RatingFIFA' if '_y' in x else x for x in df.columns]
#df.filter(like="_x").rename(columns=str.title)#.add_prefix('Team').add_suffix('FIFARating'))#.columns.str.replace('_X',''))
#df.filter(like="_x").columns.str.title().add_prefix('Team').columns.str.strip('_X')
df = df.drop(columns=df.filter(like='UpdateRating'))
df = df.drop(columns=df.filter(like='TeamRating'))
df

,Unnamed: 0,GameID,Date,Team,Opponent,TeamGoals,OpponentGoals,Result,TeamShots,OpponentShots,TeamShotsonTarget,OpponentShotsonTarget,TeamFouls,OpponentFouls,TeamCorners,OpponentCorners,TeamYellowCards,OpponentYellowCards,TeamRedCards,OpponentRedCards,O2.5,U2.5,TeamWinOdds,DrawOdds,OpponentWinOdds,Venue,TeamELO,OpponentELO,ELODif,TeamOverallRatingFIFA,TeamAttackRatingFIFA,TeamMidfieldRatingFIFA,TeamDefenseRatingFIFA,OpponentOverallRatingFIFA,OpponentAttackRatingFIFA,OpponentMidfieldRatingFIFA,OpponentDefenseRatingFIFA
0,0,0,2000-08-19,Liverpool,Bradford,1,0,W,16,3,10,2,8,8,6,1,1,1,0,0,NaN,NaN,NaN,NaN,NaN,Home,1770.149048,1578.722046,191.427002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0,2000-08-19,Bradford,Liverpool,0,1,L,3,16,2,10,8,8,1,6,1,1,0,0,NaN,NaN,NaN,NaN,NaN,Away,1578.722046,1770.149048,-191.427002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1,2000-08-19,Tottenham,Ipswich,3,1,W,20,15,6,5,14,13,3,4,0,0,0,0,NaN,NaN,NaN,NaN,NaN,Home,1676.797729,1638.084229,38.713501,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1,2000-08-19,Ipswich,Tottenham,1,3,L,15,20,5,6,13,14,4,3,0,0,0,0,NaN,NaN,NaN,NaN,NaN,Away,1638.084229,1676.797729,-38.713501,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2,2000-08-19,Sunderland,Arsenal,1,0,W,8,14,2,7,10,21,2,9,3,1,0,1,NaN,NaN,NaN,NaN,NaN,Home,1712.126343,1871.710449,-159.584106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16933,16933,8466,2023-09-30,Wolves,Man City,2,1,W,3,23,1,8,18,12,0,6,5,4,0,0,1.53,2.23,8.00,5.75,1.33,Home,1694.077148,2085.755371,-391.678223,76.0,75.0,77.0,76.0,85.0,87.0,86.0,83.0
16934,16934,8467,2023-10-01,Brentford,Forest,1,1,D,18,6,5,1,10,6,11,1,2,1,0,1,2.10,1.73,2.70,3.10,2.75,Away,1794.999390,1677.817871,117.181519,76.0,75.0,76.0,76.0,77.0,75.0,77.0,75.0
16935,16935,8467,2023-10-01,Forest,Brentford,1,1,D,6,18,1,5,6,10,1,11,1,2,1,0,2.10,1.73,2.75,3.10,2.70,Home,1677.817871,1794.999390,-117.181519,77.0,75.0,77.0,75.0,76.0,75.0,76.0,76.0
16936,16936,8468,2023-10-02,Fulham,Chelsea,0,2,L,10,11,3,4,15,12,8,1,1,4,0,0,1.98,1.87,3.60,3.50,2.05,Home,1734.691162,1756.802246,-22.111084,77.0,76.0,77.0,76.0,80.0,77.0,81.0,78.0
16937,16937,8468,2023-10-02,Chelsea,Fulham,2,0,W,11,10,4,3,12,15,1,8,4,1,0,0,1.98,1.87,2.05,3.50,3.60,Away,1756.802246,1734.691162,22.111084,80.0,77.0,81.0,78.0,77.0,76.0,77.0,76.0

In [373]:
df[df['Team'] == 'Reading']

,Unnamed: 0,GameID,Date,Team,Opponent,TeamGoals,OpponentGoals,Result,TeamShots,OpponentShots,TeamShotsonTarget,OpponentShotsonTarget,TeamFouls,OpponentFouls,TeamCorners,OpponentCorners,TeamYellowCards,OpponentYellowCards,TeamRedCards,OpponentRedCards,O2.5,U2.5,TeamWinOdds,DrawOdds,OpponentWinOdds,Venue,TeamELO,OpponentELO,ELODif,TeamOverallRatingFIFA,TeamAttackRatingFIFA,TeamMidfieldRatingFIFA,TeamDefenseRatingFIFA,OpponentOverallRatingFIFA,OpponentAttackRatingFIFA,OpponentMidfieldRatingFIFA,OpponentDefenseRatingFIFA
4571,4571,2285,2006-08-19,Reading,Middlesbrough,3,2,W,14,7,9,5,8,15,8,2,1,3,0,0,2.14,1.65,2.50,3.10,2.80,Home,1671.349365,1720.103394,-48.754028,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4586,4586,2293,2006-08-23,Reading,Aston Villa,1,2,L,5,11,3,6,6,9,7,2,1,2,1,0,2.04,1.73,4.00,3.25,1.90,Away,1679.266968,1669.133179,10.133789,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4596,4596,2298,2006-08-26,Reading,Wigan,0,1,L,5,15,3,5,14,12,10,4,2,2,0,0,2.04,1.73,4.00,3.25,1.90,Away,1673.008301,1639.299072,33.709229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4635,4635,2317,2006-09-11,Reading,Man City,1,0,W,12,15,7,8,6,16,6,4,0,4,0,1,2.05,1.68,2.30,3.10,3.10,Home,1666.080566,1670.927368,-4.846802,NaN,NaN,NaN,NaN,85.0,87.0,86.0,83.0
4636,4636,2318,2006-09-16,Reading,Sheffield United,2,1,W,8,14,2,7,6,12,7,8,1,2,0,0,2.15,1.61,2.80,3.10,2.50,Away,1676.101318,1574.342407,101.758911,NaN,NaN,NaN,NaN,73.0,72.0,74.0,72.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9780,9780,4890,2013-04-20,Reading,Norwich,1,2,L,14,19,6,9,12,8,8,8,3,2,0,0,1.84,1.96,5.25,3.80,1.75,Away,1563.806152,1620.789673,-56.983521,71.0,72.0,68.0,71.0,73.0,73.0,73.0,73.0
9810,9810,4905,2013-04-28,Reading,QPR,0,0,D,13,15,7,5,12,14,9,7,0,2,0,0,1.86,1.94,2.55,3.50,2.88,Home,1560.512329,1561.896729,-1.384399,71.0,72.0,68.0,71.0,75.0,76.0,75.0,72.0
9816,9816,4908,2013-05-04,Reading,Fulham,4,2,W,20,18,13,13,7,14,3,3,1,2,0,0,1.72,2.11,5.25,3.90,1.73,Away,1559.497070,1664.989502,-105.492432,71.0,72.0,68.0,71.0,77.0,80.0,74.0,74.0
9858,9858,4929,2013-05-14,Reading,Man City,0,2,L,11,27,7,20,6,7,4,10,0,1,0,0,1.55,2.38,6.00,4.33,1.60,Home,1576.803101,1873.171875,-296.368774,71.0,72.0,69.0,71.0,82.0,85.0,82.0,81.0
9865,9865,4932,2013-05-19,Reading,West Ham,2,4,L,17,21,7,12,8,14,4,6,1,2,0,0,1.64,2.21,5.75,4.00,1.67,Away,1575.167603,1650.771240,-75.603638,71.0,72.0,69.0,71.0,74.0,76.0,73.0,72.0

In [372]:
df.isna().sum()

Unnamed: 0                       0
GameID                           0
Date                             0
Team                             0
Opponent                         0
                              ...
TeamDefenseRatingFIFA         5640
OpponentOverallRatingFIFA     5640
OpponentAttackRatingFIFA      5640
OpponentMidfieldRatingFIFA    5640
OpponentDefenseRatingFIFA     5640
Length: 37, dtype: int64

In [352]:
df

,Unnamed: 0,GameID,Date,Team,Opponent,TeamGoals,OpponentGoals,Result,TeamShots,OpponentShots,TeamShotsonTarget,OpponentShotsonTarget,TeamFouls,OpponentFouls,TeamCorners,OpponentCorners,TeamYellowCards,OpponentYellowCards,TeamRedCards,OpponentRedCards,O2.5,U2.5,TeamWinOdds,DrawOdds,OpponentWinOdds,Venue,TeamELO,OpponentELO,ELODif,TeamOverallRatingFIFA,TeamAttackRatingFIFA,TeamMidfieldRatingFIFA,TeamDefenseRatingFIFA,OpponentOverallRatingFIFA,OpponentAttackRatingFIFA,OpponentMidfieldRatingFIFA,OpponentDefenseRatingFIFA,update,team,overall,attack,midfield,defense
0,0,0,2000-08-19,Liverpool,Bradford,1,0,W,16,3,10,2,8,8,6,1,1,1,0,0,NaN,NaN,NaN,NaN,NaN,Home,1770.149048,1578.722046,191.427002,83.0,84.0,82.0,84.0,83.0,84.0,82.0,84.0,NaT,NaN,NaN,NaN,NaN,NaN
1,1,0,2000-08-19,Bradford,Liverpool,0,1,L,3,16,2,10,8,8,1,6,1,1,0,0,NaN,NaN,NaN,NaN,NaN,Away,1578.722046,1770.149048,-191.427002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2006-08-30,Liverpool,83.0,84.0,82.0,84.0
2,2,1,2000-08-19,Tottenham,Ipswich,3,1,W,20,15,6,5,14,13,3,4,0,0,0,0,NaN,NaN,NaN,NaN,NaN,Home,1676.797729,1638.084229,38.713501,81.0,81.0,80.0,79.0,81.0,81.0,80.0,79.0,NaT,NaN,NaN,NaN,NaN,NaN
3,3,1,2000-08-19,Ipswich,Tottenham,1,3,L,15,20,5,6,13,14,4,3,0,0,0,0,NaN,NaN,NaN,NaN,NaN,Away,1638.084229,1676.797729,-38.713501,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2006-08-30,Tottenham,81.0,81.0,80.0,79.0
4,4,2,2000-08-19,Sunderland,Arsenal,1,0,W,8,14,2,7,10,21,2,9,3,1,0,1,NaN,NaN,NaN,NaN,NaN,Home,1712.126343,1871.710449,-159.584106,75.0,73.0,67.0,71.0,75.0,73.0,67.0,71.0,2006-08-30,Arsenal,82.0,82.0,84.0,81.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16933,16933,8466,2023-09-30,Wolves,Man City,2,1,W,3,23,1,8,18,12,0,6,5,4,0,0,1.53,2.23,8.00,5.75,1.33,Home,1694.077148,2085.755371,-391.678223,76.0,75.0,77.0,76.0,76.0,75.0,77.0,76.0,2023-09-26,Man City,85.0,87.0,86.0,83.0
16934,16934,8467,2023-10-01,Brentford,Forest,1,1,D,18,6,5,1,10,6,11,1,2,1,0,1,2.10,1.73,2.70,3.10,2.75,Away,1794.999390,1677.817871,117.181519,76.0,75.0,76.0,76.0,76.0,75.0,76.0,76.0,2023-09-26,Forest,77.0,75.0,77.0,75.0
16935,16935,8467,2023-10-01,Forest,Brentford,1,1,D,6,18,1,5,6,10,1,11,1,2,1,0,2.10,1.73,2.75,3.10,2.70,Home,1677.817871,1794.999390,-117.181519,77.0,75.0,77.0,75.0,77.0,75.0,77.0,75.0,2023-09-26,Brentford,76.0,75.0,76.0,76.0
16936,16936,8468,2023-10-02,Fulham,Chelsea,0,2,L,10,11,3,4,15,12,8,1,1,4,0,0,1.98,1.87,3.60,3.50,2.05,Home,1734.691162,1756.802246,-22.111084,77.0,76.0,77.0,76.0,77.0,76.0,77.0,76.0,2023-09-26,Chelsea,80.0,77.0,81.0,78.0
16937,16937,8468,2023-10-02,Chelsea,Fulham,2,0,W,11,10,4,3,12,15,1,8,4,1,0,0,1.98,1.87,2.05,3.50,3.60,Away,1756.802246,1734.691162,22.111084,80.0,77.0,81.0,78.0,80.0,77.0,81.0,78.0,2023-09-26,Fulham,77.0,76.0,77.0,76.0

In [378]:
fbref = sd.FBref('ENG-Premier League', '2019')

[10/04/23 16:14:37] INFO     Saving cached data to /Users/Gautham/soccerdata/data/FBref               ]8;id=112485;file:///Users/Gautham/miniconda3/envs/dl_hw1/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=937485;file:///Users/Gautham/miniconda3/envs/dl_hw1/lib/python3.10/site-packages/soccerdata/_common.py#89\89]8;;\

In [384]:
fbref.read_team_match_stats(stat_type='possession', team='Arsenal').head(10)

d Utd-Arsenal      247
                                  2019-10-27 Arsenal-Crystal Palace     187

                                                                             \
                                                                    Mid 3rd
league             season team    game
ENG-Premier League 1920   Arsenal 2019-08-11 Newcastle Utd-Arsenal      383
                                  2019-08-17 Arsenal-Burnley            235
                                  2019-08-24 Liverpool-Arsenal          230
                                  2019-09-01 Arsenal-Tottenham          263
                                  2019-09-15 Watford-Arsenal            279
                                  2019-09-22 Arsenal-Aston Villa        224
                                  2019-09-30 Manchester Utd-Arsenal     200
                                  2019-10-06 Arsenal-Bournemouth        284
                                  2019-10-21 Sheffield Utd-Arsenal      307
                                  2019-10-27 Arsenal-Crystal Palace     263

                                                                             \
                                                                    Att 3rd
league             season team    game
ENG-Premier League 1920   Arsenal 2019-08-11 Newcastle Utd-Arsenal      162
                                  2019-08-17 Arsenal-Burnley            187
                                  2019-08-24 Liverpool-Arsenal          112
                                  2019-09-01 Arsenal-Tottenham          237
                                  2019-09-15 Watford-Arsenal            117
                                  2019-09-22 Arsenal-Aston Villa        222
                                  2019-09-30 Manchester Utd-Arsenal     144
                                  2019-10-06 Arsenal-Bournemouth        165
                                  2019-10-21 Sheffield Utd-Arsenal      239
                                  2019-10-27 Arsenal-Crystal Palace     162

                                                                             \
                                                                    Att Pen
league             season team    game
ENG-Premier League 1920   Arsenal 2019-08-11 Newcastle Utd-Arsenal       24
                                  2019-08-17 Arsenal-Burnley             26
                                  2019-08-24 Liverpool-Arsenal           11
                                  2019-09-01 Arsenal-Tottenham           34
                                  2019-09-15 Watford-Arsenal             15
                                  2019-09-22 Arsenal-Aston Villa         38
                                  2019-09-30 Manchester Utd-Arsenal      21
                                  2019-10-06 Arsenal-Bournemouth         36
                                  2019-10-21 Sheffield Utd-Arsenal       27
                                  2019-10-27 Arsenal-Crystal Palace      26

                                                                          \
                                                                    Live
league             season team    game
ENG-Premier League 1920   Arsenal 2019-08-11 Newcastle Utd-Arsenal   771
                                  2019-08-17 Arsenal-Burnley         693
                                  2019-08-24 Liverpool-Arsenal       693
                                  2019-09-01 Arsenal-Tottenham       627
                                  2019-09-15 Watford-Arsenal         577
                                  2019-09-22 Arsenal-Aston Villa     614
                                  2019-09-30 Manchester Utd-Arsenal  525
                                  2019-10-06 Arsenal-Bournemouth     618
                                  2019-10-21 Sheffield Utd-Arsenal   788
                                  2019-10-27 Arsenal-Crystal Palace  607

                                                                    Take-Ons  \
                                                                         Att
league             season team    game
ENG-Premier League 1920   Arsenal 2019-08-11 Newcastle Utd-Arsenal        25
                                  2019-08-17 Arsenal-Burnley              20
                                  2019-08-24 Liverpool-Arsenal            21
                                  2019-09-01 Arsenal-Tottenham            17
                                  2019-09-15 Watford-Arsenal              19
                                  2019-09-22 Arsenal-Aston Villa          19
                                  2019-09-30 Manchester Utd-Arsenal       16
                                  2019-10-06 Arsenal-Bournemouth          17
                                  2019-10-21 Sheffield Utd-Arsenal        29
                                  2019-10-27 Arsenal-Crystal Palace       14

                                                                          \
                                                                    Succ
league             season team    game
ENG-Premier League 1920   Arsenal 2019-08-11 Newcastle Utd-Arsenal    12
                                  2019-08-17 Arsenal-Burnley          14
                                  2019-08-24 Liverpool-Arsenal        14
                                  2019-09-01 Arsenal-Tottenham        14
                                  2019-09-15 Watford-Arsenal          13
                                  2019-09-22 Arsenal-Aston Villa      13
                                  2019-09-30 Manchester Utd-Arsenal    8
                                  2019-10-06 Arsenal-Bournemouth      12
                                  2019-10-21 Sheffield Utd-Arsenal    20
                                  2019-10-27 Arsenal-Crystal Palace    8

                                                                           \
                                                                    Succ%
league             season team    game
ENG-Premier League 1920   Arsenal 2019-08-11 Newcastle Utd-Arsenal   48.0
                                  2019-08-17 Arsenal-Burnley         70.0
                                  2019-08-24 Liverpool-Arsenal       66.7
                                  2019-09-01 Arsenal-Tottenham       82.4
                                  2019-09-15 Watford-Arsenal         68.4
                                  2019-09-22 Arsenal-Aston Villa     68.4
                                  2019-09-30 Manchester Utd-Arsenal  50.0
                                  2019-10-06 Arsenal-Bournemouth     70.6
                                  2019-10-21 Sheffield Utd-Arsenal   69.0
                                  2019-10-27 Arsenal-Crystal Palace  57.1

                                                                          \
                                                                    Tkld
league             season team    game
ENG-Premier League 1920   Arsenal 2019-08-11 Newcastle Utd-Arsenal    13
                                  2019-08-17 Arsenal-Burnley           6
                                  2019-08-24 Liverpool-Arsenal         7
                                  2019-09-01 Arsenal-Tottenham         3
                                  2019-09-15 Watford-Arsenal           6
                                  2019-09-22 Arsenal-Aston Villa       6
                                  2019-09-30 Manchester Utd-Arsenal    8
                                  2019-10-06 Arsenal-Bournemouth       5
                                  2019-10-21 Sheffield Utd-Arsenal     9
                                  2019-10-27 Arsenal-Crystal Palace    6

                                                                           \
                                                                    Tkld%
league             season team    game
ENG-Premier League 1920   Arsenal 2019-08-11 Newcastle Utd-Arsenal   52.0
                                  2019-08-17 Arsenal-Burnley         30.0
                                  2019-08-24 Liverpool-Arsenal       33.3
                                  2019-09-01 Arsenal-Tottenham       17.6
                                  2019-09-15 Watford-Arsenal         31.6
                                  2019-09-22 Arsenal-Aston Villa     31.6
                                  2019-09-30 Manchester Utd-Arsenal  50.0
                                  2019-10-06 Arsenal-Bournemouth     29.4
                                  2019-10-21 Sheffield Utd-Arsenal   31.0
                                  2019-10-27 Arsenal-Crystal Palace  42.9

                                                                    Carries  \
                                                                    Carries
league             season team    game
ENG-Premier League 1920   Arsenal 2019-08-11 Newcastle Utd-Arsenal      454
                                  2019-08-17 Arsenal-Burnley            423
                                  2019-08-24 Liverpool-Arsenal          393
                                  2019-09-01 Arsenal-Tottenham          361
                                  2019-09-15 Watford-Arsenal            359
                                  2019-09-22 Arsenal-Aston Villa        412
                                  2019-09-30 Manchester Utd-Arsenal     240
                                  2019-10-06 Arsenal-Bournemouth        304
                                  2019-10-21 Sheffield Utd-Arsenal      471
                                  2019-10-27 Arsenal-Crystal Palace     346

                                                                             \
                                                                    TotDist
league             season team    game
ENG-Premier League 1920   Arsenal 2019-08-11 Newcastle Utd-Arsenal     2132
                                  2019-08-17 Arsenal-Burnley           2686
                                  2019-08-24 Liverpool-Arsenal         2118
                                  2019-09-01 Arsenal-Tottenham         2245
                                  2019-09-15 Watford-Arsenal           2401
                                  2019-09-22 Arsenal-Aston Villa       2650
                                  2019-09-30 Manchester Utd-Arsenal    1348
                                  2019-10-06 Arsenal-Bournemouth       1989
                                  2019-10-21 Sheffield Utd-Arsenal     2835
                                  2019-10-27 Arsenal-Crystal Palace    2318

                                                                             \
                                                                    PrgDist
league             season team    game
ENG-Premier League 1920   Arsenal 2019-08-11 Newcastle Utd-Arsenal     1136
                                  2019-08-17 Arsenal-Burnley           1413
                                  2019-08-24 Liverpool-Arsenal         1152
                                  2019-09-01 Arsenal-Tottenham         1280
                                  2019-09-15 Watford-Arsenal           1277
                                  2019-09-22 Arsenal-Aston Villa       1681
                                  2019-09-30 Manchester Utd-Arsenal     701
                                  2019-10-06 Arsenal-Bournemouth       1029
                                  2019-10-21 Sheffield Utd-Arsenal     1501
                                  2019-10-27 Arsenal-Crystal Palace    1401

                                                                              \
                                                                    PrgC 1/3
league             season team    game
ENG-Premier League 1920   Arsenal 2019-08-11 Newcastle Utd-Arsenal    20  20
                                  2019-08-17 Arsenal-Burnley          32  22
                                  2019-08-24 Liverpool-Arsenal        14  13
                                  2019-09-01 Arsenal-Tottenham        21  14
                                  2019-09-15 Watford-Arsenal          18  14
                                  2019-09-22 Arsenal-Aston Villa      30  14
                                  2019-09-30 Manchester Utd-Arsenal   19  13
                                  2019-10-06 Arsenal-Bournemouth      17  12
                                  2019-10-21 Sheffield Utd-Arsenal    29  17
                                  2019-10-27 Arsenal-Crystal Palace   23  13

                                                                             \
                                                                    CPA Mis
league             season team    game
ENG-Premier League 1920   Arsenal 2019-08-11 Newcastle Utd-Arsenal    4  15
                                  2019-08-17 Arsenal-Burnley         11  14
                                  2019-08-24 Liverpool-Arsenal        2  18
                                  2019-09-01 Arsenal-Tottenham        8  19
                                  2019-09-15 Watford-Arsenal          4  17
                                  2019-09-22 Arsenal-Aston Villa     11  12
                                  2019-09-30 Manchester Utd-Arsenal   7  15
                                  2019-10-06 Arsenal-Bournemouth      6  18
                                  2019-10-21 Sheffield Utd-Arsenal    9  16
                                  2019-10-27 Arsenal-Crystal Palace   5  15

                                                                         \
                                                                    Dis
league             season team    game
ENG-Premier League 1920   Arsenal 2019-08-11 Newcastle Utd-Arsenal   13
                                  2019-08-17 Arsenal-Burnley         10
                                  2019-08-24 Liverpool-Arsenal       18
                                  2019-09-01 Arsenal-Tottenham       10
                                  2019-09-15 Watford-Arsenal         11
                                  2019-09-22 Arsenal-Aston Villa     14
                                  2019-09-30 Manchester Utd-Arsenal   7
                                  2019-10-06 Arsenal-Bournemouth      9
                                  2019-10-21 Sheffield Utd-Arsenal   12
                                  2019-10-27 Arsenal-Crystal Palace   8

                                                                    Receiving  \
                                                                          Rec
league             season team    game
ENG-Premier League 1920   Arsenal 2019-08-11 Newcastle Utd-Arsenal        561
                                  2019-08-17 Arsenal-Burnley              471
                                  2019-08-24 Liverpool-Arsenal            471
                                  2019-09-01 Arsenal-Tottenham            406
                                  2019-09-15 Watford-Arsenal              405
                                  2019-09-22 Arsenal-Aston Villa          426
                                  2019-09-30 Manchester Utd-Arsenal       303
                                  2019-10-06 Arsenal-Bournemouth          362
                                  2019-10-21 Sheffield Utd-Arsenal        576
                                  2019-10-27 Arsenal-Crystal Palace       394

                                                                          \
                                                                    PrgR
league             season team    game
ENG-Premier League 1920   Arsenal 2019-08-11 Newcastle Utd-Arsenal    47
                                  2019-08-17 Arsenal-Burnley          33
                                  2019-08-24 Liverpool-Arsenal        28
                                  2019-09-01 Arsenal-Tottenham        65
                                  2019-09-15 Watford-Arsenal          30
                                  2019-09-22 Arsenal-Aston Villa      60
                                  2019-09-30 Manchester Utd-Arsenal   30
                                  2019-10-06 Arsenal-Bournemouth      49
                                  2019-10-21 Sheffield Utd-Arsenal    67
                                  2019-10-27 Arsenal-Crystal Palace   51

                                                                         time  \

league             season team    game
ENG-Premier League 1920   Arsenal 2019-08-11 Newcastle Utd-Arsenal   14:00:00
                                  2019-08-17 Arsenal-Burnley         12:30:00
                                  2019-08-24 Liverpool-Arsenal       17:30:00
                                  2019-09-01 Arsenal-Tottenham       16:30:00
                                  2019-09-15 Watford-Arsenal         16:30:00
                                  2019-09-22 Arsenal-Aston Villa     16:30:00
                                  2019-09-30 Manchester Utd-Arsenal  20:00:00
                                  2019-10-06 Arsenal-Bournemouth     14:00:00
                                  2019-10-21 Sheffield Utd-Arsenal   20:00:00
                                  2019-10-27 Arsenal-Crystal Palace  16:30:00

                                                                                                          match_report

league             season team    game
ENG-Premier League 1920   Arsenal 2019-08-11 Newcastle Utd-Arsenal   /en/matches/1405a610/Newcastle-United-Arsenal-...
                                  2019-08-17 Arsenal-Burnley         /en/matches/ff7eda21/Arsenal-Burnley-August-17...
                                  2019-08-24 Liverpool-Arsenal       /en/matches/102b241e/Liverpool-Arsenal-August-...
                                  2019-09-01 Arsenal-Tottenham       /en/matches/0b6b8aaf/North-London-Derby-Arsena...
                                  2019-09-15 Watford-Arsenal         /en/matches/8257eda8/Watford-Arsenal-September...
                                  2019-09-22 Arsenal-Aston Villa     /en/matches/d5fa0563/Arsenal-Aston-Villa-Septe...
                                  2019-09-30 Manchester Utd-Arsenal  /en/matches/ce7501cd/Manchester-United-Arsenal...
                                  2019-10-06 Arsenal-Bournemouth     /en/matches/9575566f/Arsenal-Bournemouth-Octob...
                                  2019-10-21 Sheffield Utd-Arsenal   /en/matches/f63044fd/Sheffield-United-Arsenal-...
                                  2019-10-27 Arsenal-Crystal Palace  /en/matches/077b30ff/Arsenal-Crystal-Palace-Oc...

In [453]:
elo_df = pd.read_csv(f'/Users/Gautham/Projects/sports_betting/cache/LaLiga/elo.csv')
elo = sd.ClubElo('ESP-La Liga')
elo.read_by_date('2023-09-26')

[10/06/23 17:38:43] INFO     Saving cached data to /Users/Gautham/soccerdata/data/ClubElo             ]8;id=866367;file:///Users/Gautham/miniconda3/envs/dl_hw1/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=286344;file:///Users/Gautham/miniconda3/envs/dl_hw1/lib/python3.10/site-packages/soccerdata/_common.py#89\89]8;;\

,rank,country,level,elo,from,to,league
team,,,,,,,
Man City,1.0,ENG,1,2085.755371,2023-09-24,2023-09-30,ENG-Premier League
Liverpool,2.0,ENG,1,1965.252197,2023-09-25,2023-09-30,ENG-Premier League
Bayern,3.0,GER,1,1949.225708,2023-09-24,2023-09-30,GER-Bundesliga
Arsenal,4.0,ENG,1,1926.775513,2023-09-25,2023-09-30,ENG-Premier League
Inter,5.0,ITA,1,1911.968140,2023-09-25,2023-09-27,ITA-Serie A
...,...,...,...,...,...,...,...
FCB Magpies,NaN,GIB,0,859.540894,2023-08-18,2023-10-24,NaN
Atletic Club Escaldes,NaN,AND,0,845.504089,2023-08-18,2023-10-24,NaN
Cosmos,NaN,SMR,0,696.818665,2023-08-02,2023-10-24,NaN
Tre Penne,NaN,SMR,0,685.562805,2023-08-02,2023-10-24,NaN
La Fiorita,NaN,SMR,0,666.206604,2023-08-02,2023-10-24,NaN

In [454]:
d1 = pd.to_datetime(elo_df.iloc[-1].Date).date()
d2 = d.today()
print(d1, d2)
dd = [d1 + timedelta(days=x) for x in range((d2-d1).days + 1)]
df = pd.DataFrame()
for d in dd:
    print(str(d))
    df1 = elo.read_by_date(str(d))
    df = pd.concat([df, df1])
df

2023-10-02 2023-10-06
2023-10-02
2023-10-03
2023-10-04
2023-10-05
2023-10-06

,rank,country,level,elo,from,to,league
team,,,,,,,
Man City,1.0,ENG,1,2070.030518,2023-10-01,2023-10-03,ENG-Premier League
Liverpool,2.0,ENG,1,1955.643311,2023-10-01,2023-10-03,ENG-Premier League
Bayern,3.0,GER,1,1948.552246,2023-10-01,2023-10-03,GER-Bundesliga
Arsenal,4.0,ENG,1,1932.627441,2023-10-01,2023-10-03,ENG-Premier League
Real Madrid,5.0,ESP,1,1917.377075,2023-10-01,2023-10-03,ESP-La Liga
...,...,...,...,...,...,...,...
FCB Magpies,NaN,GIB,0,859.540894,2023-08-18,2023-10-24,NaN
Atletic Club Escaldes,NaN,AND,0,845.504089,2023-08-18,2023-10-24,NaN
Cosmos,NaN,SMR,0,696.818665,2023-08-02,2023-10-24,NaN
Tre Penne,NaN,SMR,0,685.562805,2023-08-02,2023-10-24,NaN
La Fiorita,NaN,SMR,0,666.206604,2023-08-02,2023-10-24,NaN

In [458]:
df = df.drop_duplicates().reset_index()
df[df['league'] == 'ESP-La Liga']#[df['team'] == 'Man City']

,level_0,index,team,rank,country,level,elo,from,to,league
4,4,4,Real Madrid,5.0,ESP,1,1917.377075,2023-10-01,2023-10-03,ESP-La Liga
8,8,8,Barcelona,9.0,ESP,1,1877.362915,2023-10-01,2023-10-03,ESP-La Liga
12,12,12,Atletico,13.0,ESP,1,1853.257080,2023-10-02,2023-10-03,ESP-La Liga
24,24,24,Sociedad,25.0,ESP,1,1786.735352,2023-10-01,2023-10-03,ESP-La Liga
39,39,39,Sevilla,40.0,ESP,1,1727.113281,2023-10-02,2023-10-02,ESP-La Liga
...,...,...,...,...,...,...,...,...,...,...
1402,1402,1402,Celta,84.0,ESP,1,1637.960205,2023-10-06,2023-10-08,ESP-La Liga
1426,1426,1426,Granada,NaN,ESP,1,1598.866821,2023-10-06,2023-10-08,ESP-La Liga
1432,1432,1432,Almeria,NaN,ESP,1,1590.259521,2023-10-06,2023-10-06,ESP-La Liga
1436,1436,1436,Las Palmas,NaN,ESP,1,1588.030640,2023-10-06,2023-10-08,ESP-La Liga
1440,1440,1440,Alaves,NaN,ESP,1,1585.350830,2023-10-06,2023-10-08,ESP-La Liga