In [664]:
#%pip install soccerdata
#%pip install tpot
#%pip install pandasql
!pip install sqlalchemy==1.4.46

Collecting sqlalchemy==1.4.46
  Downloading SQLAlchemy-1.4.46-cp37-cp37m-macosx_10_15_x86_64.whl (1.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━0.0/1.6 MB? eta-:--:--━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━1.0/1.6 MB28.8 MB/s eta0:00:01━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸1.6/1.6 MB34.5 MB/s eta0:00:01━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━1.6/1.6 MB20.8 MB/s eta0:00:00
Requirement already satisfied: greenlet!=0.4.17 in /Users/Gautham/miniconda3/envs/ai_env/lib/python3.7/site-packages (from sqlalchemy==1.4.46) (2.0.2)
Requirement already satisfied: importlib-metadata in /Users/Gautham/miniconda3/envs/ai_env/lib/python3.7/site-packages (from sqlalchemy==1.4.46) (4.2.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /Users/Gautham/miniconda3/envs/ai_env/lib/python3.7/site-packages (from importlib-metadata->sqlalchemy==1.4.46) (4.7.1)
Requirement already satisfied: zipp>=0.5 in /Users/Gautham/miniconda3/envs/ai_env/lib/python3.7/site-packages (from importlib-metadata->sqlalchemy==1.4.46) (3.8.1)
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.21
    Uninstalling SQLAlchemy-2.0.21:
      Successfully uninstalled SQLAlchemy-2.0.21
Successfully installed sqlalchemy-1.4.46

In [114]:
import soccerdata as sd 
import pandas as pd
import os
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 10)

In [115]:
# Create scraper class instance for the Premier League
clubelo = sd.ClubElo('ENG-Premier League')
fifa = sd.SoFIFA()
#print(five38.available_leagues())
# Fetch dataframes

[09/21/23 11:25:50] INFO     Saving cached data to /Users/Gautham/soccerdata/data/ClubElo             ]8;id=325235;file:///Users/Gautham/miniconda3/envs/ai_env/lib/python3.7/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=374733;file:///Users/Gautham/miniconda3/envs/ai_env/lib/python3.7/site-packages/soccerdata/_common.py#89\89]8;;\

                    INFO     Saving cached data to /Users/Gautham/soccerdata/data/SoFIFA              ]8;id=52439;file:///Users/Gautham/miniconda3/envs/ai_env/lib/python3.7/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=888124;file:///Users/Gautham/miniconda3/envs/ai_env/lib/python3.7/site-packages/soccerdata/_common.py#89\89]8;;\

                    INFO     No seasons provided. Will retrieve data for the last 5 seasons.         ]8;id=550849;file:///Users/Gautham/miniconda3/envs/ai_env/lib/python3.7/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=210097;file:///Users/Gautham/miniconda3/envs/ai_env/lib/python3.7/site-packages/soccerdata/_common.py#288\288]8;;\

In [7]:
games = clubelo.read_by_date('2022-08-05')
games

,rank,country,level,elo,from,to,league
team,,,,,,,
Liverpool,1.0,ENG,1,2035.034180,2022-05-29,2022-08-06,ENG-Premier League
Man City,2.0,ENG,1,2025.127930,2022-05-29,2022-08-07,ENG-Premier League
Real Madrid,3.0,ESP,1,1983.036499,2022-05-29,2022-08-14,ESP-La Liga
Bayern,4.0,GER,1,1957.980835,2022-05-19,2022-08-05,GER-Bundesliga
Chelsea,5.0,ENG,1,1899.036499,2022-05-29,2022-08-06,ENG-Premier League
...,...,...,...,...,...,...,...
Escale,NaN,AND,0,809.113892,2022-07-28,2023-06-27,NaN
Atletic Club Escaldes,NaN,AND,0,806.759766,2022-07-28,2023-06-27,NaN
Tre Fiori,NaN,SMR,0,741.013428,2022-07-29,2023-06-27,NaN
Tre Penne,NaN,SMR,0,691.847778,2022-07-29,2023-06-27,NaN
La Fiorita,NaN,SMR,0,670.337097,2022-07-29,2023-06-27,NaN

In [8]:
elos = pd.DataFrame()

In [9]:
games = clubelo.read_team_history('Man City')
games#games[games['league'] == 'ENG-Premier League']#.filter(like='Wol')

            rank      team country  level          elo         to
from
1946-07-07   NaN  Man City     ENG      2  1365.066040 1946-09-04
1946-09-05   NaN  Man City     ENG      2  1372.480469 1946-09-07
1946-09-08   NaN  Man City     ENG      2  1369.613770 1946-09-14
1946-09-15   NaN  Man City     ENG      2  1383.733887 1946-09-18
1946-09-19   NaN  Man City     ENG      2  1385.578369 1946-09-21
...          ...       ...     ...    ...          ...        ...
2023-09-17   1.0  Man City     ENG      1  2091.449463 2023-09-19
2023-09-20   1.0  Man City     ENG      1  2091.449463 2023-09-23
2023-09-24   1.0  Man City     ENG      1  2091.449463 2023-09-30
2023-10-01   1.0  Man City     ENG      1  2091.449463 2023-10-02
2023-10-03   1.0  Man City     ENG      1  2091.449463 2023-12-31

[6078 rows x 6 columns]

In [10]:

games = fifa.read_teams()
games

[09/19/23 12:24:08] ERROR    Error while scraping https://sofifa.com. Retrying... (attempt 1 of 5).  ]8;id=741306;file:///Users/Gautham/miniconda3/envs/ai_env/lib/python3.7/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=150618;file:///Users/Gautham/miniconda3/envs/ai_env/lib/python3.7/site-packages/soccerdata/_common.py#343\343]8;;\
                             Traceback (most recent call last):
                               File
                             "/Users/Gautham/miniconda3/envs/ai_env/lib/python3.7/site-packages/socc
                             erdata/_common.py", line 336, in _download_and_save
                                 response.raise_for_status()
                               File
                             "/Users/Gautham/miniconda3/envs/ai_env/lib/python3.7/site-packages/requ
                             ests/models.py", line 1021, in raise_for_status
                                 raise HTTPError(http_error_msg, response=self)
                             requests.exceptions.HTTPError: 403 Client Error: Forbidden for url:
                             https://sofifa.com/

[09/19/23 12:24:10] ERROR    Error while scraping https://sofifa.com. Retrying... (attempt 2 of 5).  ]8;id=330020;file:///Users/Gautham/miniconda3/envs/ai_env/lib/python3.7/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=802740;file:///Users/Gautham/miniconda3/envs/ai_env/lib/python3.7/site-packages/soccerdata/_common.py#343\343]8;;\
                             Traceback (most recent call last):
                               File
                             "/Users/Gautham/miniconda3/envs/ai_env/lib/python3.7/site-packages/socc
                             erdata/_common.py", line 336, in _download_and_save
                                 response.raise_for_status()
                               File
                             "/Users/Gautham/miniconda3/envs/ai_env/lib/python3.7/site-packages/requ
                             ests/models.py", line 1021, in raise_for_status
                                 raise HTTPError(http_error_msg, response=self)
                             requests.exceptions.HTTPError: 403 Client Error: Forbidden for url:
                             https://sofifa.com/

KeyboardInterrupt:

In [33]:
class MissingDict(dict):
    __missing__ = lambda self, key: key
map_values = {
    'Middlesboro': 'Middlesbrough',
    "Nott'm Forest": 'Forest',
    'Newcastle Utd': 'Newcastle',
    'Luton Town': 'Luton',
    'Manchester City': 'Man City',
    'Manchester Utd': 'Man United'
}
mapping = MissingDict(**map_values)

#@cache_to_csv("cache/schedule.csv", refresh_time=60)
def get_schedule():
    fbref = sd.FBref('ENG-Premier League', '2324')
    sched23 = fbref.read_schedule()

    sched23 = sched23.droplevel('league')
    sched23 = sched23.droplevel('season')

    sched23 = sched23.rename(columns={'date':'Date', 'home_team':'HomeTeam', 'away_team':'AwayTeam', 'referee': 'Referee'})
    sched23['Date'] = pd.to_datetime(sched23['Date'], yearfirst=True).dt.strftime('%m/%d/%y')
    sched23[['BbAv>2.5', 'BbAv<2.5', 'BbAvH', 'BbAvD', 'BbAvA']] = None
    sched23['HomeTeam'] = sched23['HomeTeam'].map(mapping)
    sched23['AwayTeam'] = sched23['AwayTeam'].map(mapping)
    sched23 = sched23.reset_index(drop=True)
    return sched23

sched23 = get_schedule()

[09/19/23 13:01:44] INFO     Saving cached data to /Users/Gautham/soccerdata/data/FBref               ]8;id=768431;file:///Users/Gautham/miniconda3/envs/ai_env/lib/python3.7/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=261642;file:///Users/Gautham/miniconda3/envs/ai_env/lib/python3.7/site-packages/soccerdata/_common.py#89\89]8;;\

In [35]:
sched23[sched23['HomeTeam'] == 'Man United']

,week,day,Date,time,HomeTeam,home_xg,score,away_xg,AwayTeam,attendance,venue,Referee,match_report,notes,game_id,BbAv>2.5,BbAv<2.5,BbAvH,BbAvD,BbAvA
9,1.0,Mon,08/14/23,20:00,Man United,2.2,1–0,2.2,Wolves,73358.0,Old Trafford,Simon Hooper,/en/matches/f1ecda2c/Manchester-United-Wolverh...,NaN,f1ecda2c,None,None,None,None,None
27,3.0,Sat,08/26/23,15:00,Man United,2.8,3–2,1.2,Nott'ham Forest,73595.0,Old Trafford,Stuart Attwell,/en/matches/70d9b1ab/Manchester-United-Notting...,NaN,70d9b1ab,None,None,None,None,None
45,5.0,Sat,09/16/23,15:00,Man United,1.0,1–3,1.7,Brighton,73592.0,Old Trafford,Jarred Gillett,/en/matches/ddcf2857/Manchester-United-Brighto...,NaN,ddcf2857,None,None,None,None,None
68,7.0,Sat,09/30/23,15:00,Man United,NaN,NaN,NaN,Crystal Palace,NaN,Old Trafford,NaN,None,NaN,NaN,None,None,None,None,None
83,8.0,Sat,10/07/23,15:00,Man United,NaN,NaN,NaN,Brentford,NaN,Old Trafford,NaN,None,NaN,NaN,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316,29.0,Sat,03/16/24,NaN,Man United,NaN,NaN,NaN,Sheffield Utd,NaN,Old Trafford,NaN,None,NaN,NaN,None,None,None,None,None
348,32.0,Sat,04/06/24,NaN,Man United,NaN,NaN,NaN,Liverpool,NaN,Old Trafford,NaN,None,NaN,NaN,None,None,None,None,None
370,34.0,Sat,04/20/24,NaN,Man United,NaN,NaN,NaN,Newcastle,NaN,Old Trafford,NaN,None,NaN,NaN,None,None,None,None,None
379,35.0,Sat,04/27/24,NaN,Man United,NaN,NaN,NaN,Burnley,NaN,Old Trafford,NaN,None,NaN,NaN,None,None,None,None,None
401,37.0,Sat,05/11/24,NaN,Man United,NaN,NaN,NaN,Arsenal,NaN,Old Trafford,NaN,None,NaN,NaN,None,None,None,None,None

In [109]:
espn = sd.MatchHistory('ENG-Premier League', '2324')
sched = espn.read_games()
sched.sort_values('date')[::-1].tail(20)

[09/20/23 16:45:11] INFO     Saving cached data to /Users/Gautham/soccerdata/data/MatchHistory        ]8;id=279289;file:///Users/Gautham/miniconda3/envs/ai_env/lib/python3.7/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=442523;file:///Users/Gautham/miniconda3/envs/ai_env/lib/python3.7/site-packages/soccerdata/_common.py#89\89]8;;\

ed-Everton   2.39  2.90
                          2023-01-09 Luton-West Ham             1.76  4.33

                                                               WHCD   WHCA  \
league             season game
ENG-Premier League 2324   2023-08-20 Aston Villa-Everton       3.50   3.75
                          2023-08-19 Man City-Newcastle        3.40   4.20
                          2023-08-19 Tottenham-Man United      3.50   2.15
                          2023-08-19 Wolves-Brighton           3.50   1.73
                          2023-08-19 Liverpool-Bournemouth     6.00  10.00
...                                                             ...    ...
                          2023-02-09 Chelsea-Nott'm Forest     4.33   7.50
                          2023-02-09 Burnley-Tottenham         3.40   1.83
                          2023-02-09 Brentford-Bournemouth     3.70   4.33
                          2023-02-09 Sheffield United-Everton  3.10   2.20
                          2023-01-09 Luton-West Ham            3.60   1.62

                                                               VCCH  VCCD  \
league             season game
ENG-Premier League 2324   2023-08-20 Aston Villa-Everton       1.80  3.80
                          2023-08-19 Man City-Newcastle        1.87  3.70
                          2023-08-19 Tottenham-Man United      3.00  3.75
                          2023-08-19 Wolves-Brighton           4.40  4.00
                          2023-08-19 Liverpool-Bournemouth     1.20  7.50
...                                                             ...   ...
                          2023-02-09 Chelsea-Nott'm Forest     1.40  4.75
                          2023-02-09 Burnley-Tottenham         3.60  3.70
                          2023-02-09 Brentford-Bournemouth     1.73  3.80
                          2023-02-09 Sheffield United-Everton  3.20  3.30
                          2023-01-09 Luton-West Ham            4.80  3.90

                                                                VCCA  MaxCH  \
league             season game
ENG-Premier League 2324   2023-08-20 Aston Villa-Everton        4.40   1.91
                          2023-08-19 Man City-Newcastle         4.10   1.91
                          2023-08-19 Tottenham-Man United       2.20   3.38
                          2023-08-19 Wolves-Brighton            1.75   4.40
                          2023-08-19 Liverpool-Bournemouth     12.00   1.23
...                                                              ...    ...
                          2023-02-09 Chelsea-Nott'm Forest      8.50   1.44
                          2023-02-09 Burnley-Tottenham          2.00   3.95
                          2023-02-09 Brentford-Bournemouth      4.80   1.76
                          2023-02-09 Sheffield United-Everton   2.30   3.36
                          2023-01-09 Luton-West Ham             1.70   4.99

                                                               MaxCD  MaxCA  \
league             season game
ENG-Premier League 2324   2023-08-20 Aston Villa-Everton        3.92   4.68
                          2023-08-19 Man City-Newcastle         4.05   4.76
                          2023-08-19 Tottenham-Man United       3.96   2.33
                          2023-08-19 Wolves-Brighton            4.21   1.88
                          2023-08-19 Liverpool-Bournemouth      8.60  14.50
...                                                              ...    ...
                          2023-02-09 Chelsea-Nott'm Forest      5.20   8.50
                          2023-02-09 Burnley-Tottenham          3.91   2.06
                          2023-02-09 Brentford-Bournemouth      4.10   5.00
                          2023-02-09 Sheffield United-Everton   3.50   2.42
                          2023-01-09 Luton-West Ham             4.35   1.78

                                                               AvgCH  AvgCD  \
league             season game
ENG-Premier League 2324   2023-08-20 Aston Villa-Everton        1.84   3.82
                          2023-08-19 Man City-Newcastle         1.84   3.78
                          2023-08-19 Tottenham-Man United       3.01   3.78
                          2023-08-19 Wolves-Brighton            4.17   4.06
                          2023-08-19 Liverpool-Bournemouth      1.20   7.69
...                                                              ...    ...
                          2023-02-09 Chelsea-Nott'm Forest      1.40   4.84
                          2023-02-09 Burnley-Tottenham          3.64   3.79
                          2023-02-09 Brentford-Bournemouth      1.73   3.98
                          2023-02-09 Sheffield United-Everton   3.12   3.36
                          2023-01-09 Luton-West Ham             4.67   4.02

                                                               AvgCA  \
league             season game
ENG-Premier League 2324   2023-08-20 Aston Villa-Everton        4.24
                          2023-08-19 Man City-Newcastle         4.32
                          2023-08-19 Tottenham-Man United       2.25
                          2023-08-19 Wolves-Brighton            1.81
                          2023-08-19 Liverpool-Bournemouth     12.70
...                                                              ...
                          2023-02-09 Chelsea-Nott'm Forest      8.03
                          2023-02-09 Burnley-Tottenham          1.99
                          2023-02-09 Brentford-Bournemouth      4.75
                          2023-02-09 Sheffield United-Everton   2.35
                          2023-01-09 Luton-West Ham             1.73

                                                               B365C>2.5  \
league             season game
ENG-Premier League 2324   2023-08-20 Aston Villa-Everton            1.73
                          2023-08-19 Man City-Newcastle             1.85
                          2023-08-19 Tottenham-Man United           1.53
                          2023-08-19 Wolves-Brighton                1.53
                          2023-08-19 Liverpool-Bournemouth          1.25
...                                                                  ...
                          2023-02-09 Chelsea-Nott'm Forest          1.73
                          2023-02-09 Burnley-Tottenham              1.67
                          2023-02-09 Brentford-Bournemouth          1.80
                          2023-02-09 Sheffield United-Everton       2.04
                          2023-01-09 Luton-West Ham                 1.73

                                                               B365C<2.5  \
league             season game
ENG-Premier League 2324   2023-08-20 Aston Villa-Everton            2.10
                          2023-08-19 Man City-Newcastle             2.05
                          2023-08-19 Tottenham-Man United           2.50
                          2023-08-19 Wolves-Brighton                2.50
                          2023-08-19 Liverpool-Bournemouth          4.00
...                                                                  ...
                          2023-02-09 Chelsea-Nott'm Forest          2.10
                          2023-02-09 Burnley-Tottenham              2.20
                          2023-02-09 Brentford-Bournemouth          2.00
                          2023-02-09 Sheffield United-Everton       1.86
                          2023-01-09 Luton-West Ham                 2.10

                                                               PC>2.5  PC<2.5  \
league             season game
ENG-Premier League 2324   2023-08-20 Aston Villa-Everton         1.78    2.14
                          2023-08-19 Man City-Newcastle          1.86    2.05
                          2023-08-19 Tottenham-Man United        1.54    2.61
                          2023-08-19 Wolves-Brighton             1.55    2.60
                          2023-08-19 Liverpool-Bournemouth       1.33    3.48
...                                                               ...     ...
                          2023-02-09 Chelsea-Nott'm Forest       1.78    2.12
                          2023-02-09 Burnley-Tottenham           1.69    2.28
                          2023-02-09 Brentford-Bournemouth       1.83    2.07
                          2023-02-09 Sheffield United-Everton    2.05    1.87
                          2023-01-09 Luton-West Ham              1.76    2.17

                                                               MaxC>2.5  \
league             season game
ENG-Premier League 2324   2023-08-20 Aston Villa-Everton           1.82
                          2023-08-19 Man City-Newcastle            1.89
                          2023-08-19 Tottenham-Man United          1.55
                          2023-08-19 Wolves-Brighton               1.61
                          2023-08-19 Liverpool-Bournemouth         1.32
...                                                                 ...
                          2023-02-09 Chelsea-Nott'm Forest         1.80
                          2023-02-09 Burnley-Tottenham             1.73
                          2023-02-09 Brentford-Bournemouth         1.85
                          2023-02-09 Sheffield United-Everton      2.13
                          2023-01-09 Luton-West Ham                1.77

                                                               MaxC<2.5  \
league             season game
ENG-Premier League 2324   2023-08-20 Aston Villa-Everton           2.23
                          2023-08-19 Man City-Newcastle            2.20
                          2023-08-19 Tottenham-Man United          2.65
                          2023-08-19 Wolves-Brighton               2.60
                          2023-08-19 Liverpool-Bournemouth         4.00
...                                                                 ...
                          2023-02-09 Chelsea-Nott'm Forest         2.28
                          2023-02-09 Burnley-Tottenham             2.29
                          2023-02-09 Brentford-Bournemouth         2.13
                          2023-02-09 Sheffield United-Everton      1.90
                          2023-01-09 Luton-West Ham                2.29

                                                               AvgC>2.5  \
league             season game
ENG-Premier League 2324   2023-08-20 Aston Villa-Everton           1.76
                          2023-08-19 Man City-Newcastle            1.80
                          2023-08-19 Tottenham-Man United          1.51
                          2023-08-19 Wolves-Brighton               1.56
                          2023-08-19 Liverpool-Bournemouth         1.28
...                                                                 ...
                          2023-02-09 Chelsea-Nott'm Forest         1.73
                          2023-02-09 Burnley-Tottenham             1.68
                          2023-02-09 Brentford-Bournemouth         1.80
                          2023-02-09 Sheffield United-Everton      2.03
                          2023-01-09 Luton-West Ham                1.73

                                                               AvgC<2.5  AHCh  \
league             season game
ENG-Premier League 2324   2023-08-20 Aston Villa-Everton           2.09 -0.75
                          2023-08-19 Man City-Newcastle            2.04 -0.50
                          2023-08-19 Tottenham-Man United          2.54  0.25
                          2023-08-19 Wolves-Brighton               2.46  0.75
                          2023-08-19 Liverpool-Bournemouth         3.77 -2.00
...                                                                 ...   ...
                          2023-02-09 Chelsea-Nott'm Forest         2.15 -1.25
                          2023-02-09 Burnley-Tottenham             2.23  0.50
                          2023-02-09 Brentford-Bournemouth         2.06 -0.75
                          2023-02-09 Sheffield United-Everton      1.82  0.25
                          2023-01-09 Luton-West Ham                2.16  0.75

                                                               B365CAHH  \
league             season game
ENG-Premier League 2324   2023-08-20 Aston Villa-Everton           2.03
                          2023-08-19 Man City-Newcastle            1.87
                          2023-08-19 Tottenham-Man United          1.94
                          2023-08-19 Wolves-Brighton               1.88
                          2023-08-19 Liverpool-Bournemouth         1.86
...                                                                 ...
                          2023-02-09 Chelsea-Nott'm Forest         1.92
                          2023-02-09 Burnley-Tottenham             1.88
                          2023-02-09 Brentford-Bournemouth         1.97
                          2023-02-09 Sheffield United-Everton      1.89
                          2023-01-09 Luton-West Ham                1.93

                                                               B365CAHA  \
league             season game
ENG-Premier League 2324   2023-08-20 Aston Villa-Everton           1.78
                          2023-08-19 Man City-Newcastle            2.06
                          2023-08-19 Tottenham-Man United          1.99
                          2023-08-19 Wolves-Brighton               2.05
                          2023-08-19 Liverpool-Bournemouth         2.07
...                                                                 ...
                          2023-02-09 Chelsea-Nott'm Forest         2.01
                          2023-02-09 Burnley-Tottenham             2.05
                          2023-02-09 Brentford-Bournemouth         1.96
                          2023-02-09 Sheffield United-Everton      2.04
                          2023-01-09 Luton-West Ham                2.00

                                                               PCAHH  PCAHA  \
league             season game
ENG-Premier League 2324   2023-08-20 Aston Villa-Everton        2.09   1.83
                          2023-08-19 Man City-Newcastle         1.87   2.06
                          2023-08-19 Tottenham-Man United       1.93   2.00
                          2023-08-19 Wolves-Brighton            1.87   2.06
                          2023-08-19 Liverpool-Bournemouth      1.85   2.08
...                                                              ...    ...
                          2023-02-09 Chelsea-Nott'm Forest      1.93   2.00
                          2023-02-09 Burnley-Tottenham          1.88   2.04
                          2023-02-09 Brentford-Bournemouth      1.96   1.96
                          2023-02-09 Sheffield United-Everton   1.88   2.05
                          2023-01-09 Luton-West Ham             1.94   1.98

                                                               MaxCAHH  \
league             season game
ENG-Premier League 2324   2023-08-20 Aston Villa-Everton          2.15
                          2023-08-19 Man City-Newcastle           1.89
                          2023-08-19 Tottenham-Man United         2.02
                          2023-08-19 Wolves-Brighton              1.91
                          2023-08-19 Liverpool-Bournemouth        1.91
...                                                                ...
                          2023-02-09 Chelsea-Nott'm Forest        1.96
                          2023-02-09 Burnley-Tottenham            1.94
                          2023-02-09 Brentford-Bournemouth        1.99
                          2023-02-09 Sheffield United-Everton     1.94
                          2023-01-09 Luton-West Ham               2.01

                                                               MaxCAHA  \
league             season game
ENG-Premier League 2324   2023-08-20 Aston Villa-Everton          1.87
                          2023-08-19 Man City-Newcastle           2.09
                          2023-08-19 Tottenham-Man United         2.00
                          2023-08-19 Wolves-Brighton              2.08
                          2023-08-19 Liverpool-Bournemouth        2.11
...                                                                ...
                          2023-02-09 Chelsea-Nott'm Forest        2.05
                          2023-02-09 Burnley-Tottenham            2.06
                          2023-02-09 Brentford-Bournemouth        2.00
                          2023-02-09 Sheffield United-Everton     2.07
                          2023-01-09 Luton-West Ham               2.00

                                                               AvgCAHH  \
league             season game
ENG-Premier League 2324   2023-08-20 Aston Villa-Everton          2.07
                          2023-08-19 Man City-Newcastle           1.85
                          2023-08-19 Tottenham-Man United         1.89
                          2023-08-19 Wolves-Brighton              1.85
                          2023-08-19 Liverpool-Bournemouth        1.84
...                                                                ...
                          2023-02-09 Chelsea-Nott'm Forest        1.91
                          2023-02-09 Burnley-Tottenham            1.88
                          2023-02-09 Brentford-Bournemouth        1.92
                          2023-02-09 Sheffield United-Everton     1.85
                          2023-01-09 Luton-West Ham               1.93

                                                               AvgCAHA
league             season game
ENG-Premier League 2324   2023-08-20 Aston Villa-Everton          1.80
                          2023-08-19 Man City-Newcastle           2.03
                          2023-08-19 Tottenham-Man United         1.96
                          2023-08-19 Wolves-Brighton              2.01
                          2023-08-19 Liverpool-Bournemouth        2.03
...                                                                ...
                          2023-02-09 Chelsea-Nott'm Forest        1.96
                          2023-02-09 Burnley-Tottenham            2.00
                          2023-02-09 Brentford-Bournemouth        1.94
                          2023-02-09 Sheffield United-Everton     2.01
                          2023-01-09 Luton-West Ham               1.93

[20 rows x 104 columns]

In [40]:
sched23 = sched
sched23 = sched23.droplevel('league')
sched23 = sched23.droplevel('season')

sched23 = sched23.rename(columns={'date':'Date', 'home_team':'HomeTeam', 'away_team':'AwayTeam', 'referee': 'Referee'})
sched23['Date'] = pd.to_datetime(sched23['Date'], yearfirst=True).dt.strftime('%m/%d/%y')
#sched23['FTHG'] = sched23['score'].str[0].astype('float')
#sched23['FTAG'] = sched23['score'].str[-1].astype('float')
sched23[['BbAv>2.5', 'BbAv<2.5', 'BbAvH', 'BbAvD', 'BbAvA']] = None
sched23 = sched23.reset_index(drop=True)
sched23
#sched23['Date'] = pd.to_datetime(sched23['Date'], dayfirst=True)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,B365>2.5,B365<2.5,P>2.5,P<2.5,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,AHh,B365AHH,B365AHA,PAHH,PAHA,MaxAHH,MaxAHA,AvgAHH,AvgAHA,B365CH,B365CD,B365CA,BWCH,BWCD,BWCA,IWCH,IWCD,IWCA,PSCH,PSCD,PSCA,WHCH,WHCD,WHCA,VCCH,VCCD,VCCA,MaxCH,MaxCD,MaxCA,AvgCH,AvgCD,AvgCA,B365C>2.5,B365C<2.5,PC>2.5,PC<2.5,MaxC>2.5,MaxC<2.5,AvgC>2.5,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BbAv>2.5,BbAv<2.5,BbAvH,BbAvD,BbAvA
0,01/09/23,Luton,West Ham,1,2,A,0,1,A,P Tierney,16,9,1,3,8,13,9,6,1,1,0,0,4.75,3.80,1.73,4.50,3.80,1.75,4.70,3.80,1.73,4.82,4.04,1.75,3.75,3.50,1.75,5.00,3.80,1.70,5.00,4.20,1.78,4.70,3.94,1.74,1.87,2.03,1.83,2.07,1.87,2.10,1.82,2.03,0.75,1.94,1.99,1.96,1.96,2.00,2.00,1.92,1.93,4.50,4.00,1.73,4.40,3.9,1.73,4.60,3.90,1.73,4.67,4.09,1.76,4.33,3.60,1.62,4.80,3.90,1.7,4.99,4.35,1.78,4.67,4.02,1.73,1.73,2.10,1.76,2.17,1.77,2.29,1.73,2.16,0.75,1.93,2.00,1.94,1.98,2.01,2.00,1.93,1.93,None,None,None,None,None
1,02/09/23,Brentford,Bournemouth,2,2,D,1,1,D,R Madley,21,12,7,5,6,13,5,2,1,2,0,0,1.73,3.80,4.75,1.66,4.10,4.75,1.73,3.95,4.60,1.75,4.14,4.62,1.55,3.75,4.75,1.70,3.80,4.75,1.77,4.30,4.94,1.72,4.06,4.67,1.73,2.10,1.78,2.13,1.81,2.18,1.74,2.12,-0.75,1.95,1.98,1.95,1.95,1.96,2.01,1.91,1.95,1.73,4.00,4.50,1.71,3.9,4.60,1.75,3.85,4.60,1.75,4.01,4.86,1.62,3.70,4.33,1.73,3.80,4.8,1.76,4.10,5.00,1.73,3.98,4.75,1.80,2.00,1.83,2.07,1.85,2.13,1.80,2.06,-0.75,1.97,1.96,1.96,1.96,1.99,2.00,1.92,1.94,None,None,None,None,None
2,02/09/23,Brighton,Newcastle,3,1,H,1,0,H,S Attwell,15,9,6,2,14,17,5,3,4,4,0,0,2.50,3.80,2.55,2.60,3.75,2.45,2.55,3.80,2.50,2.59,3.94,2.58,2.25,3.40,2.60,2.50,3.70,2.55,2.62,4.10,2.61,2.55,3.87,2.55,1.50,2.63,1.50,2.68,1.52,2.72,1.49,2.65,0.00,1.94,1.99,1.95,1.95,1.98,2.00,1.92,1.93,2.50,3.80,2.50,2.55,3.7,2.50,2.55,3.55,2.60,2.64,3.87,2.59,2.30,3.40,2.50,2.60,3.75,2.5,2.83,3.97,2.78,2.55,3.81,2.58,1.50,2.63,1.51,2.69,1.57,2.90,1.48,2.70,0.00,1.99,1.94,1.98,1.94,2.04,2.07,1.92,1.95,None,None,None,None,None
3,02/09/23,Burnley,Tottenham,2,5,A,1,2,A,D England,16,20,4,10,15,9,7,4,4,3,0,0,3.60,4.00,1.85,3.80,3.90,1.85,3.75,3.95,1.90,3.97,4.04,1.88,3.40,3.40,1.85,3.90,3.75,1.85,3.99,4.20,1.93,3.83,3.99,1.88,1.62,2.30,1.64,2.36,1.68,2.40,1.64,2.31,0.50,2.03,1.90,2.02,1.88,2.04,1.92,1.98,1.88,3.50,3.80,1.95,3.60,3.7,1.95,3.50,3.75,2.00,3.71,3.79,2.04,3.50,3.40,1.83,3.60,3.70,2.0,3.95,3.91,2.06,3.64,3.79,1.99,1.67,2.20,1.69,2.28,1.73,2.29,1.68,2.23,0.50,1.88,2.05,1.88,2.04,1.94,2.06,1.88,2.00,None,None,None,None,None
4,02/09/23,Chelsea,Nott'm Forest,0,1,A,0,0,D,T Robinson,21,7,2,3,10,9,8,0,3,4,0,0,1.40,4.50,8.50,1.37,5.00,7.75,1.40,5.00,7.75,1.39,5.10,8.62,1.30,4.33,7.50,1.36,4.80,8.50,1.43,5.35,9.00,1.38,5.03,8.27,1.62,2.30,1.65,2.32,1.70,2.38,1.64,2.30,-1.25,1.86,2.07,1.85,2.07,1.89,2.09,1.84,2.03,1.40,4.75,7.50,1.41,4.6,7.75,1.43,4.70,7.50,1.41,5.01,8.45,1.30,4.33,7.50,1.40,4.75,8.5,1.44,5.20,8.50,1.40,4.84,8.03,1.73,2.10,1.78,2.12,1.80,2.28,1.73,2.15,-1.25,1.92,2.01,1.93,2.00,1.96,2.05,1.91,1.96,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44,12/08/23,Bournemouth,West Ham,1,1,D,0,0,D,P Bankes,14,16,5,3,9,14,10,4,1,4,0,0,2.70,3.40,2.55,2.65,3.40,2.55,2.70,3.45,2.60,2.70,3.47,2.71,2.62,3.20,2.30,2.63,3.30,2.63,2.80,3.62,2.75,2.69,3.44,2.64,1.90,2.00,1.90,1.99,1.95,2.03,1.88,1.94,0.00,1.95,1.95,1.95,1.95,1.98,1.99,1.94,1.92,2.63,3.50,2.60,2.65,3.5,2.50,2.60,3.50,2.60,2.75,3.60,2.63,2.50,3.20,2.45,2.63,3.50,2.6,2.88,3.67,2.70,2.70,3.53,2.59,1.73,2.10,1.76,2.18,1.83,2.23,1.74,2.12,0.00,2.02,1.91,2.01,1.92,2.06,1.96,1.96,1.91,None,None,None,None,None
45,12/08/23,Brighton,Luton,4,1,H,1,0,H,D Coote,27,9,12,3,11,12,6,7,2,2,0,0,1.33,5.50,9.00,1.32,5.50,9.00,1.35,5.25,8.50,1.33,5.65,9.61,1.25,4.60,8.50,1.29,5.25,10.00,1.36,6.00,10.50,1.33,5.52,9.61,1.62,2.30,1.62,2.40,1.65,2.45,1.61,2.34,-1.50,1.95,1.95,1.95,1.95,1.98,2.00,1.93,1.93,1.25,6.50,11.00,1.26,6.0,11.00,1.30,5.50,9.50,1.27,6.36,11.36,1.22,5.50,9.00,1.25,5.75,13.0,1.34,6.59,13.00,1.28,5.99,10.91,1.53,2.50,1.56,2.54,1.62,2.66,1.55,2.48,-1.75,2.01,1.92,2.00,1.91,2.14,1.93,2.00,1.86,None,None,None,None,None
46,12/08/23,Everton,Fulham,0,1,A,0,0,D,S Attwell,19,9,9,2,12,6,10,4,0,2,0,0,2.20,3.40,3.30,2.20,3.40,3.25,2.25,3.40,3.25,2.27,3.45,3.35,2.10,3.20,3.00,2.20,3.30,3.25,2.30,3.57,3.45,2.24,3.43,3.30,2.01,1.89,2.00,1.89,2.04,1.92,1.97,1.86,-0.25,1.93,1.97,1.95,1.95,1.97,2.00,1.92,1.93,2.30,3.20,3.20,2.35,3.2,3.10,2.35,3.25,3.15,2.39,3.32,3.30,2.10,3.20,3.00,2.38,3.20,3.2,2.42,3.42,3.56,2.32,3.28,3.27,2.10,1.73,2.23,1.72,2.26,1.81,2.17,1.71,-0.25,2.06,1.87,2.04,1.88,2.08,1.99,1.98,1.88,None,None,None,None,None
47,12/08/23,Newcastle,Aston Villa,5,1,H,2,1,H,A Madley,17,16,13,6,12,17,6,5,4,4,0,0,1.75,3.75,4.60,1.73,3.90,4.40,1.75,3.85,4.50,1.77,3.92,4.77,1.67,3.50,4.20,1.73,3.70,4.60,1.80,4.10,4.90,1.76,3.88,4.61,1.73,2.10,1.79,2.11,1.82,2.15,1.76,2.09,-0.75,2.01,1.89,1.99,1.92,2.02,1.94,1.97,1.89,1.62,4.00,5.25,1.65,4.0,5.00,1.63,4.10,5.25,1.68,4.20,5.29,1.55,3.80,4.60,1.60,4.10,5.5,1.71,4.30,5.64,1.65,4.14,5.17,1.67,2.20,1.72,2.23,1.73,2.34,1.68,2.22,-0.75,1.84,2.09,1.85,2.09,1.87,2.13,1.82,2.06,None,None,None,None,None
48,12/08/23,Sheffield United,Crystal Palace,0,1,A,0,0,D,J Brooks,8,24,1,8,18,11,5,5,3,0,0,0,3.00,3.30,2.38,3.00,3.25,2.40,3.00,3.25,2.40,3.28,3.22,2.43,2.75,3.10,2.30,3.10,3.10,2.38,3.31,3.42,2.48,3.12,3.24,2.41,2.20,1.67,2.26,1.69,2.28,1.74,2.21,1.68,0.25,1.84,2.06,1.85,2.06,1.86,2.11,1.81,2.05,3.60,3.20,2.15,3.75,3.1,2.15,3.70,3.15,2.15,3.98,3.22,2.17,3.50,2.88,2.05,3.90,3.10,2.1,4.00,3.28,2.23,3.81,3.16,2.16,2.50,1.53,2.59,1.56,2.65,1.57,2.54,1.53,0.25,2.10,1.83,2.10,1.84,2.12,1.86,2.05,1.83,None,None,None,None,None

In [14]:
directory = '/Users/Gautham/Downloads/archive-2/Datasets'
total_df = pd.DataFrame()
# iterate over files in
# that directory
for filename in os.listdir(directory):
    f = os.path.join(directory, filename)
    # checking if it is a file
    if os.path.isfile(f) and filename[-3:] == 'csv':
        df = pd.read_csv(f)
        #print(df)
        total_df = pd.concat([total_df,df])
        #print(total_df)
#print(total_df.columns)

In [15]:
#total_df.dropna(axis='columns', thresh=total_df.shape[0]/4)
def preprocess(total_df, source):
    total_df['TotalGoals'] = total_df['FTHG'] + total_df['FTAG']
    total_df['Date'] = pd.to_datetime(total_df['Date'], dayfirst=True)
    
    total_df = total_df.sort_values(by='Date')
    total_df['GameID'] = range(len(total_df))

    df = total_df
    if source == 'csv':
        df = total_df[['GameID', 'Date', 'HomeTeam', 'AwayTeam', 'TotalGoals', 'FTHG', 'FTAG', 'FTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 'BbAv>2.5', 'BbAv<2.5', 'AvgC>2.5', 'AvgC<2.5', 'BbAvH', 'BbAvD', 'BbAvA', 'AvgCH', 'AvgCD', 'AvgCA']]
        df['O2.5'] = np.where(df['AvgC>2.5'].isna(),df['BbAv>2.5'],df['AvgC>2.5'])
        df['U2.5'] = np.where(df['AvgC<2.5'].isna(),df['BbAv<2.5'],df['AvgC<2.5'])
        df['HomeTeamWinOdds'] = np.where(df['AvgCH'].isna(),df['BbAvH'],df['AvgCH'])
        df['AwayTeamWinOdds'] = np.where(df['AvgCA'].isna(),df['BbAvA'],df['AvgCA'])
        df['DrawOdds'] = np.where(df['AvgCD'].isna(),df['BbAvD'],df['AvgCD'])

        df.columns = ['GameID', 'Date', 'HomeTeam', 'AwayTeam', 'TotalGoals', 'HomeTeamGoals', 'AwayTeamGoals', 'Result', 'Referee', 'HomeTeamShots', 'AwayTeamShots', 'HomeTeamShotsonTarget', 'AwayTeamShotsonTarget', 'HomeTeamFouls', 'AwayTeamFouls', 'HomeTeamCorners', 'AwayTeamCorners', 'HomeTeamYellowCards', 'AwayTeamYellowCards', 'HomeTeamRedCards', 'AwayTeamRedCards', 'BbO2.5', 'BbU2.5', 'AvgO2.5', 'AvgU2.5','BbHome', 'BbDraw', 'BbAway', 'AvgH', 'AvgD', 'AvgA', 'O2.5', 'U2.5', 'HomeTeamWinOdds',  'AwayTeamWinOdds', 'DrawOdds']

        df = df[['GameID', 'Date', 'HomeTeam', 'AwayTeam', 'TotalGoals', 'HomeTeamGoals', 'AwayTeamGoals', 'Result', 'Referee', 'HomeTeamShots', 'AwayTeamShots', 'HomeTeamShotsonTarget', 'AwayTeamShotsonTarget', 'HomeTeamFouls', 'AwayTeamFouls', 'HomeTeamCorners', 'AwayTeamCorners', 'HomeTeamYellowCards', 'AwayTeamYellowCards', 'HomeTeamRedCards', 'AwayTeamRedCards', 'O2.5', 'U2.5', 'HomeTeamWinOdds', 'DrawOdds', 'AwayTeamWinOdds']]
        df = df.sort_values(by='Date')

    c1 = df.filter(like='HomeTeam').columns

    c2 = c1.str.replace('HomeTeam', 'Team')
    df = df.rename(columns={**dict(zip(c1, c2)), **dict(zip(c2, c1))})
    c1 = df.filter(like='AwayTeam').columns

    c2 = c1.str.replace('AwayTeam', 'Opponent')

    df = df.rename(columns={**dict(zip(c1, c2)), **dict(zip(c2, c1))})
    df['Venue'] = 'Home'

    c1 = df.filter(like='Team').columns
    c2 = c1.str.replace('Team', 'Opponent')

    swap = df.rename(columns={**dict(zip(c1, c2)), **dict(zip(c2, c1))})
    swap['Venue'] = 'Away'
    #print(swap)
    df = pd.concat([df,swap]).sort_index()
    #df = df.rename(columns={'Team1':'Team', 'Team2':'Opponent'})
    df = df.sort_values(by='GameID')
    return df

In [16]:
def create_predictors(df):
    df['VenueCode'] = df['Venue'].astype('category').cat.codes
    df['OpponentCode'] = df['Opponent'].astype('category').cat.codes
    df['Target'] = (df['TotalGoals'] > 2.5).astype('int')
    return df

In [17]:
new_df2023 = pd.concat([total_df, sched23])#.reset_index(drop=True)
#new_df2023
#pd.to_datetime(new_df2023['Date'],dayfirst=True)#.sort_values('Date')
df1 = preprocess(new_df2023, 'csv')
df1
#df2023 = preprocess(sched23, 'csv')

,GameID,Date,Team,Opponent,TotalGoals,TeamGoals,OpponentGoals,Result,Referee,TeamShots,OpponentShots,TeamShotsonTarget,OpponentShotsonTarget,TeamFouls,OpponentFouls,TeamCorners,OpponentCorners,TeamYellowCards,OpponentYellowCards,TeamRedCards,OpponentRedCards,O2.5,U2.5,TeamWinOdds,DrawOdds,OpponentWinOdds,Venue
0,0,2000-08-19,Charlton,Man City,4.0,4.0,0.0,H,Rob Harris,17.0,8.0,14.0,4.0,13.0,12.0,6.0,6.0,1.0,2.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,Home
0,0,2000-08-19,Man City,Charlton,4.0,0.0,4.0,H,Rob Harris,8.0,17.0,4.0,14.0,12.0,13.0,6.0,6.0,2.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,Away
1,1,2000-08-19,Chelsea,West Ham,6.0,4.0,2.0,H,Graham Barber,17.0,12.0,10.0,5.0,19.0,14.0,7.0,7.0,1.0,2.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,Home
1,1,2000-08-19,West Ham,Chelsea,6.0,2.0,4.0,H,Graham Barber,12.0,17.0,5.0,10.0,14.0,19.0,7.0,7.0,2.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,Away
2,2,2000-08-19,Middlesbrough,Coventry,4.0,3.0,1.0,A,Barry Knight,16.0,6.0,9.0,3.0,21.0,15.0,4.0,8.0,3.0,5.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,Away
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398,8435,2024-11-05,Brentford,Bournemouth,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,Away
397,8436,2024-11-05,Liverpool,Aston Villa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,Away
397,8436,2024-11-05,Aston Villa,Liverpool,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,Home
404,8437,2024-11-05,Burnley,Tottenham,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,Away
404,8437,2024-11-05,Tottenham,Burnley,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,Home

In [571]:
#total_df['Date'] = pd.to_datetime(total_df['Date'], dayfirst=True)
#total_df[total_df['Date']]

new_df2023 = pd.concat([total_df, sched23])#.reset_index(drop=True)
#new_df2023
#pd.to_datetime(new_df2023['Date'],dayfirst=True)#.sort_values('Date')
df1 = preprocess(new_df2023, 'csv')
full_df = create_predictors(df1)
full_df = full_df.reset_index(drop=True)
full_df

,GameID,Date,Team,Opponent,TotalGoals,TeamGoals,OpponentGoals,Result,Referee,TeamShots,OpponentShots,TeamShotsonTarget,OpponentShotsonTarget,TeamFouls,OpponentFouls,TeamCorners,OpponentCorners,TeamYellowCards,OpponentYellowCards,TeamRedCards,OpponentRedCards,O2.5,U2.5,TeamWinOdds,DrawOdds,OpponentWinOdds,Venue,VenueCode,OpponentCode,Target
0,0,2000-08-19,Charlton,Man City,4,4,0,H,Rob Harris,17,8,14,4,13,12,6,6,1,2,0,0,NaN,NaN,NaN,NaN,NaN,Home,1,26,1
1,0,2000-08-19,Man City,Charlton,4,0,4,H,Rob Harris,8,17,4,14,12,13,6,6,2,1,0,0,NaN,NaN,NaN,NaN,NaN,Away,0,12,1
2,1,2000-08-19,Chelsea,West Ham,6,4,2,H,Graham Barber,17,12,10,5,19,14,7,7,1,2,0,0,NaN,NaN,NaN,NaN,NaN,Home,1,44,1
3,1,2000-08-19,West Ham,Chelsea,6,2,4,H,Graham Barber,12,17,5,10,14,19,7,7,2,1,0,0,NaN,NaN,NaN,NaN,NaN,Away,0,13,1
4,2,2000-08-19,Coventry,Middlesbrough,4,1,3,A,Barry Knight,6,16,3,9,15,21,8,4,5,3,1,0,NaN,NaN,NaN,NaN,NaN,Home,1,29,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16133,8066,2023-09-17,Bournemouth,Chelsea,0,0,0,D,D Coote,13,14,4,6,15,20,1,7,1,5,0,0,1.71,2.19,4.06,3.88,1.87,Home,1,13,0
16134,8067,2023-09-17,Everton,Arsenal,1,0,1,A,S Hooper,8,13,1,4,12,10,1,11,1,1,0,0,1.68,2.23,5.74,4.37,1.57,Home,1,0,0
16135,8067,2023-09-17,Arsenal,Everton,1,1,0,A,S Hooper,13,8,4,1,10,12,11,1,1,1,0,0,1.68,2.23,1.57,4.37,5.74,Away,0,17,0
16136,8068,2023-09-18,Burnley,Nott'm Forest,2,1,1,D,R Jones,10,14,3,4,10,16,4,5,3,2,1,0,1.98,1.87,3.59,3.45,2.11,Away,0,32,0
16137,8068,2023-09-18,Nott'm Forest,Burnley,2,1,1,D,R Jones,14,10,4,3,16,10,5,4,2,3,0,1,1.98,1.87,2.11,3.45,3.59,Home,1,10,0

In [ ]:
from tpot import TPOTClassifier
#from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

#digits = load_digits()
data = 
target = total_df['TotalGoals']
X_train, X_test, y_train, y_test = train_test_split(data, target,
                                                    train_size=0.75, test_size=0.25)

pipeline_optimizer = TPOTClassifier(generations=5, population_size=20, cv=5,
                                    random_state=42, verbosity=2)
pipeline_optimizer.fit(X_train, y_train)
print(pipeline_optimizer.score(X_test, y_test))
pipeline_optimizer.export('tpot_exported_pipeline.py')

In [210]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [220]:
new_df = df.dropna(subset=['O2.5'])
train = new_df[new_df['Date'] < '2021-01-01']
test = new_df[new_df['Date'] >= '2021-01-01']

In [221]:
new_df

,GameID,Div,Date,Team,Opponent,TotalGoals,Team1Goals,Team2Goals,Result,Referee,Team1Shots,Team2Shots,Team1ShotsonTarget,Team2ShotsonTarget,Team1Fouls,Team2Fouls,Team1Corners,Team2Corners,Team1YellowCards,Team2YellowCards,Team1RedCards,Team2RedCards,O2.5,U2.5,Team1WinOdds,DrawOdds,Team2WinOdds,Venue,Target,VenueCode,OpponentCode
7,3420,E0,2009-08-15,Wolves,West Ham,2,0,2,A,C Foy,19,16,11,13,9,5,8,6,0,0,0,0,2.03,1.72,2.57,3.19,2.68,Home,0,1,42
7,3420,E0,2009-08-15,West Ham,Wolves,2,2,0,A,C Foy,16,19,13,11,5,9,6,8,0,0,0,0,2.03,1.72,2.68,3.19,2.57,Away,0,0,44
6,3421,E0,2009-08-15,Stoke,Burnley,2,2,0,H,S Bennett,12,9,5,5,15,10,3,6,2,2,0,0,2.10,1.67,1.91,3.29,4.02,Home,0,1,10
6,3421,E0,2009-08-15,Burnley,Stoke,2,0,2,H,S Bennett,9,12,5,5,10,15,6,3,2,2,0,0,2.10,1.67,4.02,3.29,1.91,Away,0,0,36
5,3422,E0,2009-08-15,Fulham,Portsmouth,1,1,0,A,M Atkinson,9,16,3,4,18,11,4,6,2,3,0,0,2.12,1.65,2.73,3.18,2.53,Away,0,0,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377,8017,E0,2022-05-22,Liverpool,Wolves,4,3,1,H,A Taylor,29,7,8,5,6,3,5,3,1,0,0,0,1.34,3.28,1.14,9.22,19.12,Home,1,1,44
379,8018,E0,2022-05-22,Norwich,Tottenham,5,0,5,A,C Kavanagh,9,19,0,13,13,7,3,2,3,1,0,0,1.58,2.40,9.99,5.59,1.31,Home,1,1,39
379,8018,E0,2022-05-22,Tottenham,Norwich,5,5,0,A,C Kavanagh,19,9,13,0,7,13,2,3,1,3,0,0,1.58,2.40,1.31,5.59,9.99,Away,1,0,30
374,8019,E0,2022-05-22,Watford,Chelsea,3,1,2,H,M Dean,8,19,3,8,9,9,3,3,0,0,0,0,1.45,2.78,16.11,7.51,1.19,Away,1,0,13
374,8019,E0,2022-05-22,Chelsea,Watford,3,2,1,H,M Dean,19,8,8,3,9,9,3,3,0,0,0,0,1.45,2.78,1.19,7.51,16.11,Home,1,1,40

In [289]:
rf.fit(train[predictors], train['Target'])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [290]:
preds = rf.predict(test[predictors])

In [291]:
from sklearn.metrics import accuracy_score, precision_score

acc = accuracy_score(test['Target'], preds)
precision_score(test['Target'], preds)

0.5385556915544676

In [292]:
acc

0.5247933884297521

In [293]:
combined = pd.DataFrame(dict(actual=test['Target'], prediction=preds))
combined

     actual  prediction
155       0           1
155       0           1
156       1           1
156       1           1
157       1           1
..      ...         ...
377       1           1
379       1           1
379       1           0
374       1           1
374       1           0

[1210 rows x 2 columns]

In [235]:
pd.crosstab(index=combined['actual'], columns=combined['prediction'])

prediction    0    1
actual
0           195  377
1           198  440

In [22]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values(by='Date')
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [711]:
cols = ['TotalGoals','TeamGoals', 'OpponentGoals', 'TeamShots', 'OpponentShots', 'TeamShotsonTarget', 'OpponentShotsonTarget', 'TeamCorners', 'OpponentCorners']
new_cols = [f'{c}Rolling' for c in cols]
new_cols

['TotalGoalsRolling',
 'TeamGoalsRolling',
 'OpponentGoalsRolling',
 'TeamShotsRolling',
 'OpponentShotsRolling',
 'TeamShotsonTargetRolling',
 'OpponentShotsonTargetRolling',
 'TeamCornersRolling',
 'OpponentCornersRolling']

In [712]:
grouped_matches = full_df.groupby('Team')
group = grouped_matches.get_group('Chelsea')
rolling_averages(group, cols, new_cols)

,GameID,Date,Team,Opponent,TotalGoals,TeamGoals,OpponentGoals,Result,Referee,TeamShots,OpponentShots,TeamShotsonTarget,OpponentShotsonTarget,TeamFouls,OpponentFouls,TeamCorners,OpponentCorners,TeamYellowCards,OpponentYellowCards,TeamRedCards,OpponentRedCards,O2.5,U2.5,TeamWinOdds,DrawOdds,OpponentWinOdds,Venue,VenueCode,OpponentCode,Target,ELODif,TotalGoalsRolling,TeamGoalsRolling,OpponentGoalsRolling,TeamShotsRolling,OpponentShotsRolling,TeamShotsonTargetRolling,OpponentShotsonTargetRolling,TeamCornersRolling,OpponentCornersRolling
71,35,2000-09-06,Chelsea,Arsenal,4,2,2,D,Mike Riley,12,13,5,5,16,22,7,6,3,1,0,0,NaN,NaN,NaN,NaN,NaN,Home,1,0,1,-80.495117,3.333333,1.666667,1.666667,14.000000,12.000000,7.666667,5.666667,7.000000,6.666667
79,39,2000-09-09,Chelsea,Newcastle,0,0,0,D,Graham Poll,10,10,3,4,21,17,6,5,3,0,0,0,NaN,NaN,NaN,NaN,NaN,Away,0,30,0,56.524780,2.666667,1.000000,1.666667,12.333333,12.333333,6.000000,5.666667,7.000000,6.333333
112,56,2000-09-17,Chelsea,Leicester,2,0,2,A,Graham Barber,16,7,10,5,16,17,15,3,3,1,0,0,NaN,NaN,NaN,NaN,NaN,Home,1,23,0,90.864990,2.000000,1.000000,1.000000,11.000000,11.666667,5.000000,6.000000,7.666667,6.000000
124,62,2000-09-23,Chelsea,Man United,6,3,3,D,Peter Jones,13,11,5,5,19,15,4,8,2,3,0,0,NaN,NaN,NaN,NaN,NaN,Away,0,27,1,-163.889771,2.000000,0.666667,1.333333,12.666667,10.000000,6.000000,4.666667,9.333333,4.666667
154,77,2000-10-01,Chelsea,Liverpool,3,3,0,H,Dermot Gallagher,11,10,5,2,14,14,3,1,1,1,0,0,NaN,NaN,NaN,NaN,NaN,Home,1,24,1,-15.239868,2.666667,1.000000,1.666667,13.000000,9.333333,6.000000,4.666667,8.333333,5.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15980,8028,2023-08-13,Chelsea,Liverpool,2,1,1,D,A Taylor,10,13,4,1,5,12,4,4,3,3,0,0,1.54,2.52,3.04,3.75,2.26,Home,1,24,0,-158.805420,2.666667,2.000000,0.666667,18.666667,5.000000,6.333333,1.333333,4.666667,1.333333
15996,8036,2023-08-20,Chelsea,West Ham,4,1,3,H,J Brooks,17,12,4,6,9,12,9,3,3,2,0,1,1.77,2.09,2.18,3.59,3.27,Away,0,44,1,13.466797,2.333333,1.333333,1.000000,16.333333,7.666667,6.333333,1.666667,4.333333,2.333333
16002,8039,2023-08-25,Chelsea,Luton,3,3,0,H,R Jones,19,11,8,1,15,12,6,4,2,3,0,0,1.63,2.33,1.26,6.12,12.06,Home,1,25,1,178.566162,3.000000,1.333333,1.666667,15.333333,11.000000,5.333333,3.333333,5.333333,3.333333
16024,8050,2023-09-02,Chelsea,Nott'm Forest,1,0,1,A,T Robinson,21,7,2,3,10,9,8,0,3,4,0,0,1.73,2.15,1.4,4.84,8.03,Home,1,32,0,111.353516,3.000000,1.666667,1.333333,15.333333,12.000000,5.333333,2.666667,6.333333,3.666667
16056,8066,2023-09-17,Chelsea,Bournemouth,0,0,0,D,D Coote,14,13,6,4,20,15,7,1,5,1,0,0,1.71,2.19,1.87,3.88,4.06,Away,0,6,0,115.216553,2.666667,1.333333,1.333333,19.000000,10.000000,4.666667,3.333333,7.666667,2.333333

In [21]:
df_rolling = full_df.groupby('Team').apply(lambda x: rolling_averages(x, cols, new_cols))
df_rolling = df_rolling.droplevel('Team')
df_rolling = df_rolling.sort_values('GameID')
df_rolling.index = range(df_rolling.shape[0])

NameError: name 'full_df' is not defined

In [714]:
df_rolling

,GameID,Date,Team,Opponent,TotalGoals,TeamGoals,OpponentGoals,Result,Referee,TeamShots,OpponentShots,TeamShotsonTarget,OpponentShotsonTarget,TeamFouls,OpponentFouls,TeamCorners,OpponentCorners,TeamYellowCards,OpponentYellowCards,TeamRedCards,OpponentRedCards,O2.5,U2.5,TeamWinOdds,DrawOdds,OpponentWinOdds,Venue,VenueCode,OpponentCode,Target,ELODif,TotalGoalsRolling,TeamGoalsRolling,OpponentGoalsRolling,TeamShotsRolling,OpponentShotsRolling,TeamShotsonTargetRolling,OpponentShotsonTargetRolling,TeamCornersRolling,OpponentCornersRolling
0,29,2000-09-05,Man City,Leeds,3,2,1,A,Graham Poll,8,6,3,1,24,18,4,9,2,2,0,0,NaN,NaN,NaN,NaN,NaN,Away,0,22,1,-229.545654,4.333333,1.666667,2.666667,12.333333,11.666667,6.333333,8.666667,6.000000,4.666667
1,30,2000-09-05,Bradford,Man United,6,0,6,H,Ian Harris,6,21,4,12,10,12,1,5,1,0,0,0,NaN,NaN,NaN,NaN,NaN,Away,0,27,1,-330.984009,1.000000,0.666667,0.333333,7.666667,14.333333,3.000000,8.000000,4.333333,6.000000
2,30,2000-09-05,Man United,Bradford,6,6,0,H,Ian Harris,21,6,12,4,12,10,5,1,0,1,0,0,NaN,NaN,NaN,NaN,NaN,Home,1,7,1,330.984009,2.666667,1.666667,1.000000,14.000000,13.000000,6.666667,7.333333,6.000000,4.000000
3,31,2000-09-05,West Ham,Sunderland,2,1,1,D,Peter Jones,16,17,9,7,14,19,11,4,3,2,0,0,NaN,NaN,NaN,NaN,NaN,Away,0,39,0,-29.575073,3.666667,1.333333,2.333333,15.333333,9.666667,8.333333,5.666667,8.333333,5.666667
4,31,2000-09-05,Sunderland,West Ham,2,1,1,D,Peter Jones,17,16,7,9,19,14,4,11,2,3,0,0,NaN,NaN,NaN,NaN,NaN,Home,1,44,0,29.575073,2.666667,1.000000,1.666667,8.666667,14.333333,3.000000,7.333333,3.666667,7.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15919,8066,2023-09-17,Chelsea,Bournemouth,0,0,0,D,D Coote,14,13,6,4,20,15,7,1,5,1,0,0,1.71,2.19,1.87,3.88,4.06,Away,0,6,0,115.216553,2.666667,1.333333,1.333333,19.000000,10.000000,4.666667,3.333333,7.666667,2.333333
15920,8067,2023-09-17,Arsenal,Everton,1,1,0,A,S Hooper,13,8,4,1,10,12,11,1,1,1,0,0,1.68,2.23,1.57,4.37,5.74,Away,0,17,0,246.614258,3.000000,2.000000,1.000000,16.666667,10.666667,6.333333,2.333333,9.333333,2.333333
15921,8067,2023-09-17,Everton,Arsenal,1,0,1,A,S Hooper,8,13,1,4,12,10,1,11,1,1,0,0,1.68,2.23,5.74,4.37,1.57,Home,1,0,0,-246.614258,3.000000,0.666667,2.333333,13.333333,12.333333,5.000000,5.666667,6.333333,3.666667
15922,8068,2023-09-18,Burnley,Nott'm Forest,2,1,1,D,R Jones,10,14,3,4,10,16,4,5,3,2,1,0,1.98,1.87,3.59,3.45,2.11,Away,0,32,0,15.627197,4.666667,1.000000,3.666667,10.333333,17.666667,2.333333,8.000000,5.666667,5.000000
15923,8068,2023-09-18,Nott'm Forest,Burnley,2,1,1,D,R Jones,14,10,4,3,16,10,5,4,2,3,0,1,1.98,1.87,2.11,3.45,3.59,Home,1,10,0,-15.627197,3.000000,1.666667,1.333333,10.666667,15.333333,3.666667,4.666667,3.000000,8.666667

In [715]:
def make_predictions(data, predictors, train, test):
    #new_df = data.dropna(subset=['O2.5'])
    
    rf.fit(train[predictors], train['Target'])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test['Target'], prediction=preds), index = test.index)
    precision = precision_score(test['Target'], preds)
    accuracy = accuracy_score(test['Target'], preds)
    return combined, precision, accuracy

In [719]:
predictors = ['VenueCode', 'OpponentCode', 'ELODif']

In [720]:
# predictions on 2023 matches
new_df = df_rolling.dropna(subset=['O2.5'])
train = new_df[new_df['Date'] < '2023-08']
test = new_df[new_df['Date'] >= '2023-08']
combined, precision, accuracy = make_predictions(df_rolling, predictors+new_cols, train, test)
precision, accuracy, combined

(0.6567164179104478,
 0.5978260869565217,
        actual  prediction
 15832       1           1
 15833       1           1
 15834       0           0
 15835       0           1
 15836       1           1
 ...       ...         ...
 15919       0           1
 15920       0           1
 15921       0           1
 15922       0           1
 15923       0           0

 [92 rows x 2 columns])

In [612]:
precision, accuracy

(0.6575342465753424, 0.6195652173913043)

In [721]:
combined = combined.merge(df_rolling[['Date', 'Team', 'Opponent', 'TotalGoals']], left_index=True, right_index=True)

In [725]:
combined #combined[combined['actual'] != combined['prediction']]

       actual  prediction       Date           Team       Opponent  TotalGoals
15832       1           1 2023-08-11        Burnley       Man City           3
15833       1           1 2023-08-11       Man City        Burnley           3
15834       0           0 2023-08-12         Fulham        Everton           1
15835       0           1 2023-08-12        Everton         Fulham           1
15836       1           1 2023-08-12       Brighton          Luton           5
...       ...         ...        ...            ...            ...         ...
15919       0           1 2023-09-17        Chelsea    Bournemouth           0
15920       0           1 2023-09-17        Arsenal        Everton           1
15921       0           1 2023-09-17        Everton        Arsenal           1
15922       0           1 2023-09-18        Burnley  Nott'm Forest           2
15923       0           0 2023-09-18  Nott'm Forest        Burnley           2

[92 rows x 6 columns]

In [724]:
merged = combined.merge(combined, left_on=['Date', 'Team'], right_on=['Date', 'Opponent'])
m = merged[merged.prediction_y == merged.prediction_x]# and merged[merged.prediction_x != merged.actual_x]
m[m.prediction_x != m.actual_x]

,actual_x,prediction_x,Date,Team_x,Opponent_x,TotalGoals_x,actual_y,prediction_y,Team_y,Opponent_y,TotalGoals_y
4,0,1,2023-08-12,West Ham,Bournemouth,2,0,1,Bournemouth,West Ham,2
5,0,1,2023-08-12,Bournemouth,West Ham,2,0,1,West Ham,Bournemouth,2
14,0,1,2023-08-14,Man United,Wolves,1,0,1,Wolves,Man United,1
15,0,1,2023-08-14,Wolves,Man United,1,0,1,Man United,Wolves,1
30,0,1,2023-08-21,Arsenal,Crystal Palace,1,0,1,Crystal Palace,Arsenal,1
...,...,...,...,...,...,...,...,...,...,...,...
53,1,0,2023-09-02,Newcastle,Brighton,4,1,0,Brighton,Newcastle,4
66,0,1,2023-09-16,Brentford,Newcastle,1,0,1,Newcastle,Brentford,1
67,0,1,2023-09-16,Newcastle,Brentford,1,0,1,Brentford,Newcastle,1
82,0,1,2023-09-17,Arsenal,Everton,1,0,1,Everton,Arsenal,1
83,0,1,2023-09-17,Everton,Arsenal,1,0,1,Arsenal,Everton,1

In [635]:
df_rolling['Team'].unique()

array(['Man City', 'Bradford', 'Man United', 'Sunderland', 'West Ham',
       'Tottenham', 'Everton', 'Ipswich', 'Leicester', 'Southampton',
       'Charlton', 'Chelsea', 'Arsenal', 'Coventry', 'Newcastle', 'Derby',
       'Middlesbrough', 'Liverpool', 'Leeds', 'Aston Villa', 'Bolton',
       'Blackburn', 'Fulham', 'West Brom', 'Birmingham', 'Middlesboro',
       'Portsmouth', 'Wolves', 'Norwich', 'Crystal Palace', 'Wigan',
       'Watford', 'Sheffield United', 'Reading', 'Hull', 'Stoke',
       'Burnley', 'Blackpool', 'Swansea', 'QPR', 'Cardiff', 'Bournemouth',
       'Brighton', 'Huddersfield', 'Brentford', "Nott'm Forest", 'Luton'],
      dtype=object)

In [104]:
elo_df = pd.DataFrame()
missing = []
for club in df_rolling['Team'].unique():
    try:
        elo = clubelo.read_team_history(club)
        elo_df = pd.concat([elo_df,elo])
    except:
        print(club)
        missing.append(club)

print(missing)

NameError: name 'df_rolling' is not defined

In [674]:
elo_df = pd.concat([elo_df, clubelo.read_team_history('Forest')])
elo_df['team'].replace(['Forest'], "Nott'm Forest", regex=True, inplace=True)
elo_df = elo_df.reset_index()

In [688]:
elo_df['to'] = pd.to_datetime(elo_df['to'],yearfirst=True)
elo_df['from'] = pd.to_datetime(elo_df['from'],yearfirst=True)
elo_df = elo_df[elo_df['from'] > '2000']

In [2]:
'''
!pip install --upgrade pandas
import pandasql as ps

sqlcode = 
select *
from full_df
inner join elo_df on full_df.Team=elo_df.team
where elo_df.from <= full_df.Date and elo_df.to >= full_df.Date

newdf = ps.sqldf(sqlcode,locals())
newdf
'''
out = full_df.merge(elo_df[['team', 'elo', 'from', 'to']], how='left', left_on=['Team'], right_on=['team'])

NameError: name 'full_df' is not defined

In [727]:
out = out.merge(elo_df[['team', 'elo', 'from', 'to']], how='left', left_on=['Opponent'], right_on=['team']) 
out = out.query('Date.between(`from_y`, `to_y`)')
out = out.reset_index(drop=True)
out

In [1]:
out

NameError: name 'out' is not defined

In [705]:
out['ELODif'] = out['elo_x'] - out['elo_y']
out = out.drop(columns=['from_x', 'from_y', 'to_x', 'to_y', 'team_x', 'team_y', 'elo_x', 'elo_y'])

In [707]:
full_df = out

In [29]:
li1 = ['Man City', 'Bradford', 'Man United', 'Sunderland', 'West Ham',
       'Tottenham', 'Everton', 'Ipswich', 'Leicester', 'Southampton',
       'Charlton', 'Chelsea', 'Arsenal', 'Coventry', 'Newcastle', 'Derby',
       'Middlesbrough', 'Liverpool', 'Leeds', 'Aston Villa', 'Bolton',
       'Blackburn', 'Fulham', 'West Brom', 'Birmingham', 'Middlesboro',
       'Portsmouth', 'Wolves', 'Norwich', 'Crystal Palace', 'Wigan',
       'Watford', 'Sheffield United', 'Reading', 'Hull', 'Stoke',
       'Burnley', 'Blackpool', 'Swansea', 'QPR', 'Cardiff', 'Bournemouth',
       'Brighton', 'Huddersfield', 'Brentford', "Nott'm Forest", 'Luton']
li2 = ['Man City', 'Charlton', 'Chelsea', 'West Ham', 'Middlesbrough', 'Coventry', 'Derby', 'Southampton', 'Everton', 'Leeds', 'Aston Villa', 'Leicester', 'Bradford', 'Liverpool', 'Sunderland', 'Arsenal', 'Tottenham', 'Ipswich', 'Man United', 'Newcastle', 'Bolton', 'Blackburn', 'Fulham', 'Middlesboro', 'West Brom', 'Birmingham', 'Portsmouth', 'Wolves', 'Norwich', 'Crystal Palace', 'Wigan', 'Watford', 'Reading', 'Sheffield United', 'Hull', 'Stoke', 'Burnley', 'Blackpool', 'QPR', 'Swansea', 'Cardiff', 'Bournemouth', 'Huddersfield', 'Brighton', 'Brentford', 'Luton Town', "Nott'ham Forest", 'Newcastle Utd', 'Manchester City', 'Sheffield Utd', 'Manchester Utd']

temp = [x for x in li2 if x not in li1]
temp

['Luton Town',
 "Nott'ham Forest",
 'Newcastle Utd',
 'Manchester City',
 'Sheffield Utd',
 'Manchester Utd']

In [102]:
directory = '/Users/Gautham/Downloads/archive-2/Datasets'
total_df = pd.DataFrame()

for filename in os.listdir(directory):
    f = os.path.join(directory, filename)
    # checking if it is a file
    
    if os.path.isfile(f) and filename[-3:] == 'csv':
        print(f)
        df = pd.read_csv(f, encoding = 'unicode_escape')
        total_df = pd.concat([total_df,df], join='outer')
print(total_df)

/Users/Gautham/Downloads/archive-2/Datasets/2016-17.csv
/Users/Gautham/Downloads/archive-2/Datasets/2006-07.csv
/Users/Gautham/Downloads/archive-2/Datasets/2020-2021.csv
/Users/Gautham/Downloads/archive-2/Datasets/2004-05.csv
/Users/Gautham/Downloads/archive-2/Datasets/2014-15.csv
/Users/Gautham/Downloads/archive-2/Datasets/2021-2022.csv
/Users/Gautham/Downloads/archive-2/Datasets/2012-13.csv
/Users/Gautham/Downloads/archive-2/Datasets/2002-03.csv
/Users/Gautham/Downloads/archive-2/Datasets/2007-08.csv
/Users/Gautham/Downloads/archive-2/Datasets/2000-01.csv
/Users/Gautham/Downloads/archive-2/Datasets/2019-20.csv
/Users/Gautham/Downloads/archive-2/Datasets/2010-11.csv
/Users/Gautham/Downloads/archive-2/Datasets/2017-18.csv
/Users/Gautham/Downloads/archive-2/Datasets/2015-16.csv
/Users/Gautham/Downloads/archive-2/Datasets/2005-06.csv
/Users/Gautham/Downloads/archive-2/Datasets/2009-10.csv
/Users/Gautham/Downloads/archive-2/Datasets/2008-09.csv
/Users/Gautham/Downloads/archive-2/Datasets/2018-19.csv
/Users/Gautham/Downloads/archive-2/Datasets/2013-14.csv
/Users/Gautham/Downloads/archive-2/Datasets/2003-04.csv
/Users/Gautham/Downloads/archive-2/Datasets/2011-12.csv
/Users/Gautham/Downloads/archive-2/Datasets/2001-02.csv
    Div      Date        HomeTeam    AwayTeam  FTHG  FTAG FTR  HTHG  HTAG HTR  \
0    E0  13/08/16         Burnley     Swansea     0     1   A     0     0   D
1    E0  13/08/16  Crystal Palace   West Brom     0     1   A     0     0   D
2    E0  13/08/16         Everton   Tottenham     1     1   D     1     0   H
3    E0  13/08/16            Hull   Leicester     2     1   H     1     0   H
4    E0  13/08/16        Man City  Sunderland     2     1   H     1     0   H
..   ..       ...             ...         ...   ...   ...  ..   ...   ...  ..
375  E0  11/05/02       Liverpool     Ipswich     5     0   H     2     0   H
376  E0  11/05/02      Man United    Charlton     0     0   D     0     0   D
377  E0  11/05/02     Southampton   Newcastle     3     1   H     2     0   H
378  E0  11/05/02      Sunderland       Derby     1     1   D     1     0   H
379  E0  11/05/02        West Ham      Bolton     2     1   H     1     0   H

           Referee  HS  AS  HST  AST  HF  AF  HC  AC  HY  AY  HR  AR  B365H  \
0           J Moss  10  17    3    9  10  14   7   4   3   2   0   0   2.40
1         C Pawson  14  13    4    3  12  15   3   6   2   2   0   0   2.00
2       M Atkinson  12  13    6    4  10  14   5   6   0   0   0   0   3.20
3           M Dean  14  18    5    5   8  17   5   3   2   2   0   0   4.50
4         R Madley  16   7    4    3  11  14   9   6   1   2   0   0   1.25
..             ...  ..  ..  ...  ...  ..  ..  ..  ..  ..  ..  ..  ..    ...
375    Dunn, S. W.  15   7    8    2  13   5   0   7   0   0   0   0    NaN
376       Poll, G.  13  11    6    6   8   7   7   4   2   0   0   0    NaN
377  D'Urso, A. P.   7  16    3    8  15  11   3   6   0   1   1   0    NaN
378   Wiley, A. G.  26   5   12    3  11  14   4   2   0   1   0   0    NaN
379     Dean, M. L  17  10   10    4   9  13   9   5   2   1   0   0    NaN

     B365D  B365A   BWH  BWD    BWA   IWH  IWD    IWA   LBH   LBD    LBA  \
0      3.3   3.25  2.45  3.1   2.95  2.50  3.3   2.65  2.45  3.25   3.10
1      3.3   4.50  2.00  3.2   3.90  2.10  3.3   3.30  2.00  3.25   4.33
2      3.4   2.40  2.95  3.2   2.40  2.65  3.3   2.50  3.10  3.40   2.40
3      3.6   1.91  4.33  3.4   1.90  3.30  3.3   2.10  4.50  3.50   1.91
4      6.5  15.00  1.22  6.0  11.50  1.25  5.5  10.30  1.25  6.50  13.00
..     ...    ...   ...  ...    ...   ...  ...    ...   ...   ...    ...
375    NaN    NaN   NaN  NaN    NaN   NaN  NaN    NaN   NaN   NaN    NaN
376    NaN    NaN   NaN  NaN    NaN   NaN  NaN    NaN   NaN   NaN    NaN
377    NaN    NaN   NaN  NaN    NaN   NaN  NaN    NaN   NaN   NaN    NaN
378    NaN    NaN   NaN  NaN    NaN   NaN  NaN    NaN   NaN   NaN    NaN
379    NaN    NaN   NaN  NaN    NaN   NaN  NaN    NaN   NaN   NaN    NaN

      PSH   PSD    PSA   WHH   WHD    WHA   VCH  VCD    VCA  Bb1X2  BbMxH  \
0    2.47  3.32   3.19  2.50  3.20   2.90  2.50  3.2   3.25   55.0   2.55
1    2.06  3.29   4.32  2.05  3.10   4.00  2.00  3.3   4.40   56.0   2.10
2    3.25  3.43   2.37  3.10  3.10   2.40  3.25  3.4   2.38   55.0   3.30
3    4.43  3.55   1.95  4.20  3.25   1.95  4.40  3.5   1.95   55.0   4.50
4    1.27  6.48  13.15  1.25  5.50  13.00  1.25  6.5  15.00   56.0   1.30
..    ...   ...    ...   ...   ...    ...   ...  ...    ...    ...    ...
375   NaN   NaN    NaN   NaN   NaN    NaN   NaN  NaN    NaN    NaN    NaN
376   NaN   NaN    NaN   NaN   NaN    NaN   NaN  NaN    NaN    NaN    NaN
377   NaN   NaN    NaN   NaN   NaN    NaN   NaN  NaN    NaN    NaN    NaN
378   NaN   NaN    NaN   NaN   NaN    NaN   NaN  NaN    NaN    NaN    NaN
379   NaN   NaN    NaN   NaN   NaN    NaN   NaN  NaN    NaN    NaN    NaN

     BbAvH  BbMxD  BbAvD  BbMxA  BbAvA  BbOU  BbMx>2.5  BbAv>2.5  BbMx<2.5  \
0     2.43   3.35   3.21   3.30   3.10  40.0      2.40      2.30      1.68
1     2.01   3.40   3.23   4.50   4.16  38.0      2.68      2.50      1.60
2     3.12   3.45   3.32   2.50   2.36  41.0      2.12      2.05      1.87
3     4.17   3.60   3.43   2.33   1.95  40.0      2.30      2.19      1.74
4     1.25   6.80   6.11  15.00  12.55  39.0      1.56      1.53      2.67
..     ...    ...    ...    ...    ...   ...       ...       ...       ...
375    NaN    NaN    NaN    NaN    NaN   NaN       NaN       NaN       NaN
376    NaN    NaN    NaN    NaN    NaN   NaN       NaN       NaN       NaN
377    NaN    NaN    NaN    NaN    NaN   NaN       NaN       NaN       NaN
378    NaN    NaN    NaN    NaN    NaN   NaN       NaN       NaN       NaN
379    NaN    NaN    NaN    NaN    NaN   NaN       NaN       NaN       NaN

     BbAv<2.5  BbAH  BbAHh  BbMxAHH  BbAvAHH  BbMxAHA  BbAvAHA  PSCH  PSCD  \
0        1.61  32.0  -0.25     2.13     2.06     1.86     1.81  2.79  3.16
1        1.52  33.0  -0.50     2.07     2.00     1.90     1.85  2.25  3.15
2        1.77  32.0   0.25     1.91     1.85     2.09     2.00  3.64  3.54
3        1.67  31.0   0.25     2.35     2.26     2.03     1.67  4.68  3.50
4        2.48  34.0  -1.50     1.81     1.73     2.20     2.14  1.25  6.50
..        ...   ...    ...      ...      ...      ...      ...   ...   ...
375       NaN   NaN    NaN      NaN      NaN      NaN      NaN   NaN   NaN
376       NaN   NaN    NaN      NaN      NaN      NaN      NaN   NaN   NaN
377       NaN   NaN    NaN      NaN      NaN      NaN      NaN   NaN   NaN
378       NaN   NaN    NaN      NaN      NaN      NaN      NaN   NaN   NaN
379       NaN   NaN    NaN      NaN      NaN      NaN      NaN   NaN   NaN

      PSCA  GBH  GBD  GBA  SBH  SBD  SBA  SJH  SJD  SJA Time  MaxH  MaxD  \
0     2.89  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN   NaN
1     3.86  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN   NaN
2     2.16  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN   NaN
3     1.92  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN   NaN
4    14.50  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN   NaN
..     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...
375    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN   NaN
376    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN   NaN
377    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN   NaN
378    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN   NaN
379    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN   NaN

     MaxA  AvgH  AvgD  AvgA  B365>2.5  B365<2.5  P>2.5  P<2.5  Max>2.5  \
0     NaN   NaN   NaN   NaN       NaN       NaN    NaN    NaN      NaN
1     NaN   NaN   NaN   NaN       NaN       NaN    NaN    NaN      NaN
2     NaN   NaN   NaN   NaN       NaN       NaN    NaN    NaN      NaN
3     NaN   NaN   NaN   NaN       NaN       NaN    NaN    NaN      NaN
4     NaN   NaN   NaN   NaN       NaN       NaN    NaN    NaN      NaN
..    ...   ...   ...   ...       ...       ...    ...    ...      ...
375   NaN   NaN   NaN   NaN       NaN       NaN    NaN    NaN      NaN
376   NaN   NaN   NaN   NaN       NaN       NaN    NaN    NaN      NaN
377   NaN   NaN   NaN   NaN       NaN       NaN    NaN    NaN      NaN
378   NaN   NaN   NaN   NaN       NaN       NaN    NaN    NaN      NaN
379   NaN   NaN   NaN   NaN       NaN       NaN    NaN    NaN      NaN

     Max<2.5  Avg>2.5  Avg<2.5  AHh  B365AHH  B365AHA  PAHH  PAHA  MaxAHH  \
0        NaN      NaN      NaN  NaN      NaN      NaN   NaN   NaN     NaN
1        NaN      NaN      NaN  NaN      NaN      NaN   NaN   NaN     NaN
2        NaN      NaN      NaN  NaN      NaN      NaN   NaN   NaN     NaN
3        NaN      NaN      NaN  NaN      NaN      NaN   NaN   NaN     NaN
4        NaN      NaN      NaN  NaN      NaN      NaN   NaN   NaN     NaN
..       ...      ...      ...  ...      ...      ...   ...   ...     ...
375      NaN      NaN      NaN  NaN      NaN      NaN   NaN   NaN     NaN
376      NaN      NaN      NaN  NaN      NaN      NaN   NaN   NaN     NaN
377      NaN      NaN      NaN  NaN      NaN      NaN   NaN   NaN     NaN
378      NaN      NaN      NaN  NaN      NaN      NaN   NaN   NaN     NaN
379      NaN      NaN      NaN  NaN      NaN      NaN   NaN   NaN     NaN

     MaxAHA  AvgAHH  AvgAHA  B365CH  B365CD  B365CA  BWCH  BWCD  BWCA  IWCH  \
0       NaN     NaN     NaN     NaN     NaN     NaN   NaN   NaN   NaN   NaN
1       NaN     NaN     NaN     NaN     NaN     NaN   NaN   NaN   NaN   NaN
2       NaN     NaN     NaN     NaN     NaN     NaN   NaN   NaN   NaN   NaN
3       NaN     NaN     NaN     NaN     NaN     NaN   NaN   NaN   NaN   NaN
4       NaN     NaN     NaN     NaN     NaN     NaN   NaN   NaN   NaN   NaN
..      ...     ...     ...     ...     ...     ...   ...   ...   ...   ...
375     NaN     NaN     NaN     NaN     NaN     NaN   NaN   NaN   NaN   NaN
376     NaN     NaN     NaN     NaN     NaN     NaN   NaN   NaN   NaN   NaN
377     NaN     NaN     NaN     NaN     NaN     NaN   NaN   NaN   NaN   NaN
378     NaN     NaN     NaN     NaN     NaN     NaN   NaN   NaN   NaN   NaN
379     NaN     NaN     NaN     NaN     NaN     NaN   NaN   NaN   NaN   NaN

     IWCD  IWCA  WHCH  WHCD  WHCA  VCCH  VCCD  VCCA  MaxCH  MaxCD  MaxCA  \
0     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN    NaN
1     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN    NaN
2     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN    NaN
3     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN    NaN
4     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN    NaN
..    ...   ...   ...   ...   ...   ...   ...   ...    ...    ...    ...
375   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN    NaN
376   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN    NaN
377   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN    NaN
378   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN    NaN
379   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN    NaN

     AvgCH  AvgCD  AvgCA  B365C>2.5  B365C<2.5  PC>2.5  PC<2.5  MaxC>2.5  \
0      NaN    NaN    NaN        NaN        NaN     NaN     NaN       NaN
1      NaN    NaN    NaN        NaN        NaN     NaN     NaN       NaN
2      NaN    NaN    NaN        NaN        NaN     NaN     NaN       NaN
3      NaN    NaN    NaN        NaN        NaN     NaN     NaN       NaN
4      NaN    NaN    NaN        NaN        NaN     NaN     NaN       NaN
..     ...    ...    ...        ...        ...     ...     ...       ...
375    NaN    NaN    NaN        NaN        NaN     NaN     NaN       NaN
376    NaN    NaN    NaN        NaN        NaN     NaN     NaN       NaN
377    NaN    NaN    NaN        NaN        NaN     NaN     NaN       NaN
378    NaN    NaN    NaN        NaN        NaN     NaN     NaN       NaN
379    NaN    NaN    NaN        NaN        NaN     NaN     NaN       NaN

     MaxC<2.5  AvgC>2.5  AvgC<2.5  AHCh  B365CAHH  B365CAHA  PCAHH  PCAHA  \
0         NaN       NaN       NaN   NaN       NaN       NaN    NaN    NaN
1         NaN       NaN       NaN   NaN       NaN       NaN    NaN    NaN
2         NaN       NaN       NaN   NaN       NaN       NaN    NaN    NaN
3         NaN       NaN       NaN   NaN       NaN       NaN    NaN    NaN
4         NaN       NaN       NaN   NaN       NaN       NaN    NaN    NaN
..        ...       ...       ...   ...       ...       ...    ...    ...
375       NaN       NaN       NaN   NaN       NaN       NaN    NaN    NaN
376       NaN       NaN       NaN   NaN       NaN       NaN    NaN    NaN
377       NaN       NaN       NaN   NaN       NaN       NaN    NaN    NaN
378       NaN       NaN       NaN   NaN       NaN       NaN    NaN    NaN
379       NaN       NaN       NaN   NaN       NaN       NaN    NaN    NaN

     MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA  GB>2.5  GB<2.5  GBAHH  GBAHA  GBAH  \
0        NaN      NaN      NaN      NaN     NaN     NaN    NaN    NaN   NaN
1        NaN      NaN      NaN      NaN     NaN     NaN    NaN    NaN   NaN
2        NaN      NaN      NaN      NaN     NaN     NaN    NaN    NaN   NaN
3        NaN      NaN      NaN      NaN     NaN     NaN    NaN    NaN   NaN
4        NaN      NaN      NaN      NaN     NaN     NaN    NaN    NaN   NaN
..       ...      ...      ...      ...     ...     ...    ...    ...   ...
375      NaN      NaN      NaN      NaN     NaN     NaN    NaN    NaN   NaN
376      NaN      NaN      NaN      NaN     NaN     NaN    NaN    NaN   NaN
377      NaN      NaN      NaN      NaN     NaN     NaN    NaN    NaN   NaN
378      NaN      NaN      NaN      NaN     NaN     NaN    NaN    NaN   NaN
379      NaN      NaN      NaN      NaN     NaN     NaN    NaN    NaN   NaN

     LBAHH  LBAHA  LBAH  B365AH  BSH  BSD  BSA  SOH  SOD  SOA  Unnamed: 48  \
0      NaN    NaN   NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN          NaN
1      NaN    NaN   NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN          NaN
2      NaN    NaN   NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN          NaN
3      NaN    NaN   NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN          NaN
4      NaN    NaN   NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN          NaN
..     ...    ...   ...     ...  ...  ...  ...  ...  ...  ...          ...
375    NaN    NaN   NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN          NaN
376    NaN    NaN   NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN          NaN
377    NaN    NaN   NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN          NaN
378    NaN    NaN   NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN          NaN
379    NaN    NaN   NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN          NaN

     Unnamed: 49  Unnamed: 50  Unnamed: 51  Unnamed: 52  Attendance  HHW  AHW  \
0            NaN          NaN          NaN          NaN         NaN  NaN  NaN
1            NaN          NaN          NaN          NaN         NaN  NaN  NaN
2            NaN          NaN          NaN          NaN         NaN  NaN  NaN
3            NaN          NaN          NaN          NaN         NaN  NaN  NaN
4            NaN          NaN          NaN          NaN         NaN  NaN  NaN
..           ...          ...          ...          ...         ...  ...  ...
375          NaN          NaN          NaN          NaN     44088.0  0.0  1.0
376          NaN          NaN          NaN          NaN     67579.0  0.0  0.0
377          NaN          NaN          NaN          NaN     31973.0  0.0  0.0
378          NaN          NaN          NaN          NaN     47989.0  2.0  0.0
379          NaN          NaN          NaN          NaN     35546.0  1.0  0.0

      HO   AO
0    NaN  NaN
1    NaN  NaN
2    NaN  NaN
3    NaN  NaN
4    NaN  NaN
..   ...  ...
375  2.0  2.0
376  1.0  3.0
377  3.0  5.0
378  6.0  5.0
379  3.0  6.0

[8020 rows x 161 columns]

In [103]:
clubelo = sd.ClubElo('ESP-La Liga')
elo = clubelo.read_team_history('Real Sociedad')

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,Bb1X2,BbMxH,BbAvH,BbMxD,BbAvD,BbMxA,BbAvA,BbOU,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA,GBH,GBD,GBA,SBH,SBD,SBA,SJH,SJD,SJA,Time,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,B365>2.5,B365<2.5,P>2.5,P<2.5,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,AHh,B365AHH,B365AHA,PAHH,PAHA,MaxAHH,MaxAHA,AvgAHH,AvgAHA,B365CH,B365CD,B365CA,BWCH,BWCD,BWCA,IWCH,IWCD,IWCA,WHCH,WHCD,WHCA,VCCH,VCCD,VCCA,MaxCH,MaxCD,MaxCA,AvgCH,AvgCD,AvgCA,B365C>2.5,B365C<2.5,PC>2.5,PC<2.5,MaxC>2.5,MaxC<2.5,AvgC>2.5,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,GB>2.5,GB<2.5,GBAHH,GBAHA,GBAH,LBAHH,LBAHA,LBAH,B365AH,BSH,BSD,BSA,SOH,SOD,SOA,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Attendance,HHW,AHW,HO,AO
0,E0,13/08/16,Burnley,Swansea,0,1,A,0,0,D,J Moss,10,17,3,9,10,14,7,4,3,2,0,0,2.40,3.3,3.25,2.45,3.1,2.95,2.50,3.3,2.65,2.45,3.25,3.10,2.47,3.32,3.19,2.50,3.20,2.90,2.50,3.2,3.25,55.0,2.55,2.43,3.35,3.21,3.30,3.10,40.0,2.40,2.30,1.68,1.61,32.0,-0.25,2.13,2.06,1.86,1.81,2.79,3.16,2.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,13/08/16,Crystal Palace,West Brom,0,1,A,0,0,D,C Pawson,14,13,4,3,12,15,3,6,2,2,0,0,2.00,3.3,4.50,2.00,3.2,3.90,2.10,3.3,3.30,2.00,3.25,4.33,2.06,3.29,4.32,2.05,3.10,4.00,2.00,3.3,4.40,56.0,2.10,2.01,3.40,3.23,4.50,4.16,38.0,2.68,2.50,1.60,1.52,33.0,-0.50,2.07,2.00,1.90,1.85,2.25,3.15,3.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,13/08/16,Everton,Tottenham,1,1,D,1,0,H,M Atkinson,12,13,6,4,10,14,5,6,0,0,0,0,3.20,3.4,2.40,2.95,3.2,2.40,2.65,3.3,2.50,3.10,3.40,2.40,3.25,3.43,2.37,3.10,3.10,2.40,3.25,3.4,2.38,55.0,3.30,3.12,3.45,3.32,2.50,2.36,41.0,2.12,2.05,1.87,1.77,32.0,0.25,1.91,1.85,2.09,2.00,3.64,3.54,2.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,13/08/16,Hull,Leicester,2,1,H,1,0,H,M Dean,14,18,5,5,8,17,5,3,2,2,0,0,4.50,3.6,1.91,4.33,3.4,1.90,3.30,3.3,2.10,4.50,3.50,1.91,4.43,3.55,1.95,4.20,3.25,1.95,4.40,3.5,1.95,55.0,4.50,4.17,3.60,3.43,2.33,1.95,40.0,2.30,2.19,1.74,1.67,31.0,0.25,2.35,2.26,2.03,1.67,4.68,3.50,1.92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,13/08/16,Man City,Sunderland,2,1,H,1,0,H,R Madley,16,7,4,3,11,14,9,6,1,2,0,0,1.25,6.5,15.00,1.22,6.0,11.50,1.25,5.5,10.30,1.25,6.50,13.00,1.27,6.48,13.15,1.25,5.50,13.00,1.25,6.5,15.00,56.0,1.30,1.25,6.80,6.11,15.00,12.55,39.0,1.56,1.53,2.67,2.48,34.0,-1.50,1.81,1.73,2.20,2.14,1.25,6.50,14.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,11/05/02,Liverpool,Ipswich,5,0,H,2,0,H,"Dunn, S. W.",15,7,8,2,13,5,0,7,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44088.0,0.0,1.0,2.0,2.0
376,E0,11/05/02,Man United,Charlton,0,0,D,0,0,D,"Poll, G.",13,11,6,6,8,7,7,4,2,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67579.0,0.0,0.0,1.0,3.0
377,E0,11/05/02,Southampton,Newcastle,3,1,H,2,0,H,"D'Urso, A. P.",7,16,3,8,15,11,3,6,0,1,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31973.0,0.0,0.0,3.0,5.0
378,E0,11/05/02,Sunderland,Derby,1,1,D,1,0,H,"Wiley, A. G.",26,5,12,3,11,14,4,2,0,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47989.0,2.0,0.0,6.0,5.0
379,E0,11/05/02,West Ham,Bolton,2,1,H,1,0,H,"Dean, M. L",17,10,10,4,9,13,9,5,2,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35546.0,1.0,0.0,3.0,6.0

In [161]:
total = pd.read_csv('/Users/Gautham/Projects/Betting/cache/total_df.csv')
dict(total.isna().sum())#.filter(like='')
#rolling = pd.read_csv('/Users/Gautham/Projects/Betting/cache/rolling.csv')
#dict(rolling.isna().sum())#.dropna(subset=['O2.5'])#.isna().sum())
#pro = pd.read_csv('/Users/Gautham/Projects/Betting/cache/processed.csv')
#pro.filter(like='O2.5').dropna(subset=['O2.5'])

{'Unnamed: 0': 0,
 'Div': 429,
 'Date': 0,
 'HomeTeam': 0,
 'AwayTeam': 0,
 'FTHG': 0,
 'FTAG': 0,
 'FTR': 0,
 'HTHG': 0,
 'HTAG': 0,
 'HTR': 0,
 'Referee': 0,
 'HS': 0,
 'AS': 0,
 'HST': 0,
 'AST': 0,
 'HF': 0,
 'AF': 0,
 'HC': 0,
 'AC': 0,
 'HY': 0,
 'AY': 0,
 'HR': 0,
 'AR': 0,
 'B365H': 760,
 'B365D': 760,
 'B365A': 760,
 'BWH': 1521,
 'BWD': 1521,
 'BWA': 1521,
 'IWH': 776,
 'IWD': 776,
 'IWA': 776,
 'LBH': 2371,
 'LBD': 2371,
 'LBA': 2371,
 'PSH': 4561,
 'PSD': 4561,
 'PSA': 4561,
 'WHH': 868,
 'WHD': 868,
 'WHA': 868,
 'VCH': 1900,
 'VCD': 1900,
 'VCA': 1900,
 'Bb1X2': 3349,
 'BbMxH': 3349,
 'BbAvH': 3349,
 'BbMxD': 3349,
 'BbAvD': 3349,
 'BbMxA': 3349,
 'BbAvA': 3349,
 'BbOU': 3349,
 'BbMx>2.5': 3349,
 'BbAv>2.5': 3349,
 'BbMx<2.5': 3349,
 'BbAv<2.5': 3349,
 'BbAH': 3359,
 'BbAHh': 3359,
 'BbMxAHH': 3359,
 'BbAvAHH': 3359,
 'BbMxAHA': 3359,
 'BbAvAHA': 3359,
 'PSCH': 6080,
 'PSCD': 6080,
 'PSCA': 6080,
 'GBH': 4270,
 'GBD': 4270,
 'GBA': 4270,
 'SBH': 4649,
 'SBD': 4649,
 'SBA': 4649,
 'SJH': 4990,
 'SJD': 4990,
 'SJA': 4990,
 'Time': 7429,
 'MaxH': 7000,
 'MaxD': 7000,
 'MaxA': 7000,
 'AvgH': 7000,
 'AvgD': 7000,
 'AvgA': 7000,
 'B365>2.5': 5997,
 'B365<2.5': 5997,
 'P>2.5': 7001,
 'P<2.5': 7001,
 'Max>2.5': 7000,
 'Max<2.5': 7000,
 'Avg>2.5': 7000,
 'Avg<2.5': 7000,
 'AHh': 7000,
 'B365AHH': 6262,
 'B365AHA': 6262,
 'PAHH': 7000,
 'PAHA': 7000,
 'MaxAHH': 7000,
 'MaxAHA': 7000,
 'AvgAHH': 7000,
 'AvgAHA': 7000,
 'B365CH': 7000,
 'B365CD': 7000,
 'B365CA': 7000,
 'BWCH': 7010,
 'BWCD': 7010,
 'BWCA': 7010,
 'IWCH': 7003,
 'IWCD': 7003,
 'IWCA': 7003,
 'WHCH': 7000,
 'WHCD': 7000,
 'WHCA': 7000,
 'VCCH': 7000,
 'VCCD': 7000,
 'VCCA': 7000,
 'MaxCH': 7000,
 'MaxCD': 7000,
 'MaxCA': 7000,
 'AvgCH': 7000,
 'AvgCD': 7000,
 'AvgCA': 7000,
 'B365C>2.5': 7000,
 'B365C<2.5': 7000,
 'PC>2.5': 7001,
 'PC<2.5': 7001,
 'MaxC>2.5': 7000,
 'MaxC<2.5': 7000,
 'AvgC>2.5': 7000,
 'AvgC<2.5': 7000,
 'AHCh': 7000,
 'B365CAHH': 7001,
 'B365CAHA': 7001,
 'PCAHH': 7000,
 'PCAHA': 7000,
 'MaxCAHH': 7001,
 'MaxCAHA': 7001,
 'AvgCAHH': 7000,
 'AvgCAHA': 7000,
 'GB>2.5': 7312,
 'GB<2.5': 7312,
 'GBAHH': 7691,
 'GBAHA': 7700,
 'GBAH': 7700,
 'LBAHH': 7728,
 'LBAHA': 7728,
 'LBAH': 7728,
 'B365AH': 7711,
 'BSH': 6169,
 'BSD': 6169,
 'BSA': 6169,
 'SOH': 7689,
 'SOD': 7689,
 'SOA': 7689,
 'Unnamed: 48': 8449,
 'Unnamed: 49': 8449,
 'Unnamed: 50': 8449,
 'Unnamed: 51': 8449,
 'Unnamed: 52': 8449,
 'Attendance': 7690,
 'HHW': 7689,
 'AHW': 7689,
 'HO': 7689,
 'AO': 7689}

In [ ]:
history = sd.MatchHistory('ENG-Premier League', year)#'2000-2023')
sched = history.read_games()